// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: task/v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTasksRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeSolution bool                   `protobuf:"varint,1,opt,name=include_solution,json=includeSolution,proto3" json:"include_solution,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	mi := &file_task_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetTasksRequest) GetIncludeSolution() bool {
	if x != nil {
		return x.IncludeSolution
	}
	return false
}

type TestCase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Order         int32                  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	IsHidden      bool                   `protobuf:"varint,5,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCase) Reset() {
	*x = TestCase{}
	mi := &file_task_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCase) ProtoMessage() {}

func (x *TestCase) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCase.ProtoReflect.Descriptor instead.
func (*TestCase) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *TestCase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCase) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *TestCase) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TestCase) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TestCase) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

type TestCaseGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Order         int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	TestCases     []*TestCase            `protobuf:"bytes,5,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCaseGroup) Reset() {
	*x = TestCaseGroup{}
	mi := &file_task_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCaseGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCaseGroup) ProtoMessage() {}

func (x *TestCaseGroup) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCaseGroup.ProtoReflect.Descriptor instead.
func (*TestCaseGroup) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *TestCaseGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCaseGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestCaseGroup) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TestCaseGroup) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *TestCaseGroup) GetTestCases() []*TestCase {
	if x != nil {
		return x.TestCases
	}
	return nil
}

type Segment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_task_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Segment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Segment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Segments      []*Segment             `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_task_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *File) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type Solution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Files         []*File                `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Solution) Reset() {
	*x = Solution{}
	mi := &file_task_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Solution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solution) ProtoMessage() {}

func (x *Solution) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solution.ProtoReflect.Descriptor instead.
func (*Solution) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Solution) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *Solution) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type AllowedRunner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Files         []*File                `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowedRunner) Reset() {
	*x = AllowedRunner{}
	mi := &file_task_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowedRunner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedRunner) ProtoMessage() {}

func (x *AllowedRunner) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedRunner.ProtoReflect.Descriptor instead.
func (*AllowedRunner) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *AllowedRunner) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *AllowedRunner) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type TaskResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TestCaseGroups  []*TestCaseGroup       `protobuf:"bytes,2,rep,name=test_case_groups,json=testCaseGroups,proto3" json:"test_case_groups,omitempty"`
	AllowedRunners  []*AllowedRunner       `protobuf:"bytes,3,rep,name=allowed_runners,json=allowedRunners,proto3" json:"allowed_runners,omitempty"`
	CompareScriptId *string                `protobuf:"bytes,4,opt,name=compare_script_id,json=compareScriptId,proto3,oneof" json:"compare_script_id,omitempty"`
	Limit           *Limit                 `protobuf:"bytes,5,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Solution        *Solution              `protobuf:"bytes,6,opt,name=solution,proto3,oneof" json:"solution,omitempty"`
	ResourceFiles   []*File                `protobuf:"bytes,7,rep,name=resource_files,json=resourceFiles,proto3" json:"resource_files,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_task_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *TaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskResponse) GetTestCaseGroups() []*TestCaseGroup {
	if x != nil {
		return x.TestCaseGroups
	}
	return nil
}

func (x *TaskResponse) GetAllowedRunners() []*AllowedRunner {
	if x != nil {
		return x.AllowedRunners
	}
	return nil
}

func (x *TaskResponse) GetCompareScriptId() string {
	if x != nil && x.CompareScriptId != nil {
		return *x.CompareScriptId
	}
	return ""
}

func (x *TaskResponse) GetLimit() *Limit {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *TaskResponse) GetSolution() *Solution {
	if x != nil {
		return x.Solution
	}
	return nil
}

func (x *TaskResponse) GetResourceFiles() []*File {
	if x != nil {
		return x.ResourceFiles
	}
	return nil
}

type GetTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskResponse        `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	mi := &file_task_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GetTasksResponse) GetTasks() []*TaskResponse {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Limit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuTime       float32                `protobuf:"fixed32,1,opt,name=cpu_time,json=cpuTime,proto3" json:"cpu_time,omitempty"`
	CpuExtraTime  float32                `protobuf:"fixed32,2,opt,name=cpu_extra_time,json=cpuExtraTime,proto3" json:"cpu_extra_time,omitempty"`
	WallTime      float32                `protobuf:"fixed32,3,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	Memory        int32                  `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Stack         int32                  `protobuf:"varint,5,opt,name=stack,proto3" json:"stack,omitempty"`
	MaxOpenFiles  int32                  `protobuf:"varint,6,opt,name=max_open_files,json=maxOpenFiles,proto3" json:"max_open_files,omitempty"`
	MaxFileSize   float32                `protobuf:"fixed32,7,opt,name=max_file_size,json=maxFileSize,proto3" json:"max_file_size,omitempty"`
	NetworkAllow  bool                   `protobuf:"varint,8,opt,name=network_allow,json=networkAllow,proto3" json:"network_allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limit) Reset() {
	*x = Limit{}
	mi := &file_task_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limit) ProtoMessage() {}

func (x *Limit) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limit.ProtoReflect.Descriptor instead.
func (*Limit) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *Limit) GetCpuTime() float32 {
	if x != nil {
		return x.CpuTime
	}
	return 0
}

func (x *Limit) GetCpuExtraTime() float32 {
	if x != nil {
		return x.CpuExtraTime
	}
	return 0
}

func (x *Limit) GetWallTime() float32 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *Limit) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Limit) GetStack() int32 {
	if x != nil {
		return x.Stack
	}
	return 0
}

func (x *Limit) GetMaxOpenFiles() int32 {
	if x != nil {
		return x.MaxOpenFiles
	}
	return 0
}

func (x *Limit) GetMaxFileSize() float32 {
	if x != nil {
		return x.MaxFileSize
	}
	return 0
}

func (x *Limit) GetNetworkAllow() bool {
	if x != nil {
		return x.NetworkAllow
	}
	return false
}

type UpdateTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	TestCaseGroups  []*TestCaseGroup       `protobuf:"bytes,2,rep,name=test_case_groups,json=testCaseGroups,proto3" json:"test_case_groups,omitempty"`
	AllowedRunners  []*AllowedRunner       `protobuf:"bytes,3,rep,name=allowed_runners,json=allowedRunners,proto3" json:"allowed_runners,omitempty"`
	CompareScriptId *string                `protobuf:"bytes,4,opt,name=compare_script_id,json=compareScriptId,proto3,oneof" json:"compare_script_id,omitempty"`
	Limit           *Limit                 `protobuf:"bytes,5,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Solution        *Solution              `protobuf:"bytes,6,opt,name=solution,proto3,oneof" json:"solution,omitempty"`
	ResourceFiles   []*File                `protobuf:"bytes,7,rep,name=resource_files,json=resourceFiles,proto3" json:"resource_files,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_task_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetTestCaseGroups() []*TestCaseGroup {
	if x != nil {
		return x.TestCaseGroups
	}
	return nil
}

func (x *UpdateTaskRequest) GetAllowedRunners() []*AllowedRunner {
	if x != nil {
		return x.AllowedRunners
	}
	return nil
}

func (x *UpdateTaskRequest) GetCompareScriptId() string {
	if x != nil && x.CompareScriptId != nil {
		return *x.CompareScriptId
	}
	return ""
}

func (x *UpdateTaskRequest) GetLimit() *Limit {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *UpdateTaskRequest) GetSolution() *Solution {
	if x != nil {
		return x.Solution
	}
	return nil
}

func (x *UpdateTaskRequest) GetResourceFiles() []*File {
	if x != nil {
		return x.ResourceFiles
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_task_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveRunnerOnCascadeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRunnerOnCascadeRequest) Reset() {
	*x = RemoveRunnerOnCascadeRequest{}
	mi := &file_task_v1_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRunnerOnCascadeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRunnerOnCascadeRequest) ProtoMessage() {}

func (x *RemoveRunnerOnCascadeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRunnerOnCascadeRequest.ProtoReflect.Descriptor instead.
func (*RemoveRunnerOnCascadeRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveRunnerOnCascadeRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

type RemoveCompareScriptOnCascadeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompareScriptId string                 `protobuf:"bytes,1,opt,name=compare_script_id,json=compareScriptId,proto3" json:"compare_script_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RemoveCompareScriptOnCascadeRequest) Reset() {
	*x = RemoveCompareScriptOnCascadeRequest{}
	mi := &file_task_v1_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCompareScriptOnCascadeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCompareScriptOnCascadeRequest) ProtoMessage() {}

func (x *RemoveCompareScriptOnCascadeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCompareScriptOnCascadeRequest.ProtoReflect.Descriptor instead.
func (*RemoveCompareScriptOnCascadeRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveCompareScriptOnCascadeRequest) GetCompareScriptId() string {
	if x != nil {
		return x.CompareScriptId
	}
	return ""
}

var File_task_v1_messages_proto protoreflect.FileDescriptor

const file_task_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x16task/v1/messages.proto\x12\atask.v1\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x0fGetTasksRequest\x12)\n" +
	"\x10include_solution\x18\x01 \x01(\bR\x0fincludeSolution\"{\n" +
	"\bTestCase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x05R\x05order\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x1b\n" +
	"\tis_hidden\x18\x05 \x01(\bR\bisHidden\"\x91\x01\n" +
	"\rTestCaseGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x14\n" +
	"\x05order\x18\x04 \x01(\x05R\x05order\x120\n" +
	"\n" +
	"test_cases\x18\x05 \x03(\v2\x11.task.v1.TestCaseR\ttestCases\"7\n" +
	"\aSegment\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"b\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12,\n" +
	"\bsegments\x18\x03 \x03(\v2\x10.task.v1.SegmentR\bsegments\"L\n" +
	"\bSolution\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12#\n" +
	"\x05files\x18\x02 \x03(\v2\r.task.v1.FileR\x05files\"Q\n" +
	"\rAllowedRunner\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12#\n" +
	"\x05files\x18\x02 \x03(\v2\r.task.v1.FileR\x05files\"\x94\x03\n" +
	"\fTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\x10test_case_groups\x18\x02 \x03(\v2\x16.task.v1.TestCaseGroupR\x0etestCaseGroups\x12?\n" +
	"\x0fallowed_runners\x18\x03 \x03(\v2\x16.task.v1.AllowedRunnerR\x0eallowedRunners\x12/\n" +
	"\x11compare_script_id\x18\x04 \x01(\tH\x00R\x0fcompareScriptId\x88\x01\x01\x12)\n" +
	"\x05limit\x18\x05 \x01(\v2\x0e.task.v1.LimitH\x01R\x05limit\x88\x01\x01\x122\n" +
	"\bsolution\x18\x06 \x01(\v2\x11.task.v1.SolutionH\x02R\bsolution\x88\x01\x01\x124\n" +
	"\x0eresource_files\x18\a \x03(\v2\r.task.v1.FileR\rresourceFilesB\x14\n" +
	"\x12_compare_script_idB\b\n" +
	"\x06_limitB\v\n" +
	"\t_solution\"?\n" +
	"\x10GetTasksResponse\x12+\n" +
	"\x05tasks\x18\x01 \x03(\v2\x15.task.v1.TaskResponseR\x05tasks\"\x82\x02\n" +
	"\x05Limit\x12\x19\n" +
	"\bcpu_time\x18\x01 \x01(\x02R\acpuTime\x12$\n" +
	"\x0ecpu_extra_time\x18\x02 \x01(\x02R\fcpuExtraTime\x12\x1b\n" +
	"\twall_time\x18\x03 \x01(\x02R\bwallTime\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\x05R\x06memory\x12\x14\n" +
	"\x05stack\x18\x05 \x01(\x05R\x05stack\x12$\n" +
	"\x0emax_open_files\x18\x06 \x01(\x05R\fmaxOpenFiles\x12\"\n" +
	"\rmax_file_size\x18\a \x01(\x02R\vmaxFileSize\x12#\n" +
	"\rnetwork_allow\x18\b \x01(\bR\fnetworkAllow\"\xa5\x03\n" +
	"\x11UpdateTaskRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12@\n" +
	"\x10test_case_groups\x18\x02 \x03(\v2\x16.task.v1.TestCaseGroupR\x0etestCaseGroups\x12?\n" +
	"\x0fallowed_runners\x18\x03 \x03(\v2\x16.task.v1.AllowedRunnerR\x0eallowedRunners\x12/\n" +
	"\x11compare_script_id\x18\x04 \x01(\tH\x01R\x0fcompareScriptId\x88\x01\x01\x12)\n" +
	"\x05limit\x18\x05 \x01(\v2\x0e.task.v1.LimitH\x02R\x05limit\x88\x01\x01\x122\n" +
	"\bsolution\x18\x06 \x01(\v2\x11.task.v1.SolutionH\x03R\bsolution\x88\x01\x01\x124\n" +
	"\x0eresource_files\x18\a \x03(\v2\r.task.v1.FileR\rresourceFilesB\x05\n" +
	"\x03_idB\x14\n" +
	"\x12_compare_script_idB\b\n" +
	"\x06_limitB\v\n" +
	"\t_solution\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12CreateTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x1cRemoveRunnerOnCascadeRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\"Q\n" +
	"#RemoveCompareScriptOnCascadeRequest\x12*\n" +
	"\x11compare_script_id\x18\x01 \x01(\tR\x0fcompareScriptIdB/Z-github.com/CSKU-Lab/task-service/grpc/task/v1b\x06proto3"

var (
	file_task_v1_messages_proto_rawDescOnce sync.Once
	file_task_v1_messages_proto_rawDescData []byte
)

func file_task_v1_messages_proto_rawDescGZIP() []byte {
	file_task_v1_messages_proto_rawDescOnce.Do(func() {
		file_task_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_v1_messages_proto_rawDesc), len(file_task_v1_messages_proto_rawDesc)))
	})
	return file_task_v1_messages_proto_rawDescData
}

var file_task_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_task_v1_messages_proto_goTypes = []any{
	(*GetTaskRequest)(nil),                      // 0: task.v1.GetTaskRequest
	(*GetTasksRequest)(nil),                     // 1: task.v1.GetTasksRequest
	(*TestCase)(nil),                            // 2: task.v1.TestCase
	(*TestCaseGroup)(nil),                       // 3: task.v1.TestCaseGroup
	(*Segment)(nil),                             // 4: task.v1.Segment
	(*File)(nil),                                // 5: task.v1.File
	(*Solution)(nil),                            // 6: task.v1.Solution
	(*AllowedRunner)(nil),                       // 7: task.v1.AllowedRunner
	(*TaskResponse)(nil),                        // 8: task.v1.TaskResponse
	(*GetTasksResponse)(nil),                    // 9: task.v1.GetTasksResponse
	(*Limit)(nil),                               // 10: task.v1.Limit
	(*UpdateTaskRequest)(nil),                   // 11: task.v1.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),                   // 12: task.v1.DeleteTaskRequest
	(*CreateTaskResponse)(nil),                  // 13: task.v1.CreateTaskResponse
	(*RemoveRunnerOnCascadeRequest)(nil),        // 14: task.v1.RemoveRunnerOnCascadeRequest
	(*RemoveCompareScriptOnCascadeRequest)(nil), // 15: task.v1.RemoveCompareScriptOnCascadeRequest
}
var file_task_v1_messages_proto_depIdxs = []int32{
	2,  // 0: task.v1.TestCaseGroup.test_cases:type_name -> task.v1.TestCase
	4,  // 1: task.v1.File.segments:type_name -> task.v1.Segment
	5,  // 2: task.v1.Solution.files:type_name -> task.v1.File
	5,  // 3: task.v1.AllowedRunner.files:type_name -> task.v1.File
	3,  // 4: task.v1.TaskResponse.test_case_groups:type_name -> task.v1.TestCaseGroup
	7,  // 5: task.v1.TaskResponse.allowed_runners:type_name -> task.v1.AllowedRunner
	10, // 6: task.v1.TaskResponse.limit:type_name -> task.v1.Limit
	6,  // 7: task.v1.TaskResponse.solution:type_name -> task.v1.Solution
	5,  // 8: task.v1.TaskResponse.resource_files:type_name -> task.v1.File
	8,  // 9: task.v1.GetTasksResponse.tasks:type_name -> task.v1.TaskResponse
	3,  // 10: task.v1.UpdateTaskRequest.test_case_groups:type_name -> task.v1.TestCaseGroup
	7,  // 11: task.v1.UpdateTaskRequest.allowed_runners:type_name -> task.v1.AllowedRunner
	10, // 12: task.v1.UpdateTaskRequest.limit:type_name -> task.v1.Limit
	6,  // 13: task.v1.UpdateTaskRequest.solution:type_name -> task.v1.Solution
	5,  // 14: task.v1.UpdateTaskRequest.resource_files:type_name -> task.v1.File
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_task_v1_messages_proto_init() }
func file_task_v1_messages_proto_init() {
	if File_task_v1_messages_proto != nil {
		return
	}
	file_task_v1_messages_proto_msgTypes[8].OneofWrappers = []any{}
	file_task_v1_messages_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_v1_messages_proto_rawDesc), len(file_task_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_v1_messages_proto_goTypes,
		DependencyIndexes: file_task_v1_messages_proto_depIdxs,
		MessageInfos:      file_task_v1_messages_proto_msgTypes,
	}.Build()
	File_task_v1_messages_proto = out.File
	file_task_v1_messages_proto_goTypes = nil
	file_task_v1_messages_proto_depIdxs = nil
}
