// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: task/v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTasksRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeSolution bool                   `protobuf:"varint,1,opt,name=include_solution,json=includeSolution,proto3" json:"include_solution,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	mi := &file_task_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetTasksRequest) GetIncludeSolution() bool {
	if x != nil {
		return x.IncludeSolution
	}
	return false
}

type TestCase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         int32                  `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCase) Reset() {
	*x = TestCase{}
	mi := &file_task_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCase) ProtoMessage() {}

func (x *TestCase) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCase.ProtoReflect.Descriptor instead.
func (*TestCase) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *TestCase) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *TestCase) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TestCase) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type TaskResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Solution         string                 `protobuf:"bytes,2,opt,name=solution,proto3" json:"solution,omitempty"`
	Testcases        []*TestCase            `protobuf:"bytes,3,rep,name=testcases,proto3" json:"testcases,omitempty"`
	AllowedRunnerIds []string               `protobuf:"bytes,4,rep,name=allowed_runner_ids,json=allowedRunnerIds,proto3" json:"allowed_runner_ids,omitempty"`
	CompareScriptId  string                 `protobuf:"bytes,5,opt,name=compare_script_id,json=compareScriptId,proto3" json:"compare_script_id,omitempty"`
	Limit            *Limit                 `protobuf:"bytes,6,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_task_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskResponse) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *TaskResponse) GetTestcases() []*TestCase {
	if x != nil {
		return x.Testcases
	}
	return nil
}

func (x *TaskResponse) GetAllowedRunnerIds() []string {
	if x != nil {
		return x.AllowedRunnerIds
	}
	return nil
}

func (x *TaskResponse) GetCompareScriptId() string {
	if x != nil {
		return x.CompareScriptId
	}
	return ""
}

func (x *TaskResponse) GetLimit() *Limit {
	if x != nil {
		return x.Limit
	}
	return nil
}

type GetTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskResponse        `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	mi := &file_task_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetTasksResponse) GetTasks() []*TaskResponse {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Limit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuTime       float32                `protobuf:"fixed32,1,opt,name=cpu_time,json=cpuTime,proto3" json:"cpu_time,omitempty"`
	CpuExtraTime  float32                `protobuf:"fixed32,2,opt,name=cpu_extra_time,json=cpuExtraTime,proto3" json:"cpu_extra_time,omitempty"`
	WallTime      float32                `protobuf:"fixed32,3,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	Memory        int32                  `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Stack         int32                  `protobuf:"varint,5,opt,name=stack,proto3" json:"stack,omitempty"`
	MaxOpenFiles  int32                  `protobuf:"varint,6,opt,name=max_open_files,json=maxOpenFiles,proto3" json:"max_open_files,omitempty"`
	MaxFileSize   float32                `protobuf:"fixed32,7,opt,name=max_file_size,json=maxFileSize,proto3" json:"max_file_size,omitempty"`
	NetworkAllow  bool                   `protobuf:"varint,8,opt,name=network_allow,json=networkAllow,proto3" json:"network_allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limit) Reset() {
	*x = Limit{}
	mi := &file_task_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limit) ProtoMessage() {}

func (x *Limit) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limit.ProtoReflect.Descriptor instead.
func (*Limit) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Limit) GetCpuTime() float32 {
	if x != nil {
		return x.CpuTime
	}
	return 0
}

func (x *Limit) GetCpuExtraTime() float32 {
	if x != nil {
		return x.CpuExtraTime
	}
	return 0
}

func (x *Limit) GetWallTime() float32 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *Limit) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Limit) GetStack() int32 {
	if x != nil {
		return x.Stack
	}
	return 0
}

func (x *Limit) GetMaxOpenFiles() int32 {
	if x != nil {
		return x.MaxOpenFiles
	}
	return 0
}

func (x *Limit) GetMaxFileSize() float32 {
	if x != nil {
		return x.MaxFileSize
	}
	return 0
}

func (x *Limit) GetNetworkAllow() bool {
	if x != nil {
		return x.NetworkAllow
	}
	return false
}

type UpsertTaskRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Solution         *string                `protobuf:"bytes,2,opt,name=solution,proto3,oneof" json:"solution,omitempty"`
	Testcases        []*TestCase            `protobuf:"bytes,3,rep,name=testcases,proto3" json:"testcases,omitempty"`
	AllowedRunnerIds []string               `protobuf:"bytes,4,rep,name=allowed_runner_ids,json=allowedRunnerIds,proto3" json:"allowed_runner_ids,omitempty"`
	CompareId        *string                `protobuf:"bytes,5,opt,name=compare_id,json=compareId,proto3,oneof" json:"compare_id,omitempty"`
	Limit            *Limit                 `protobuf:"bytes,6,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpsertTaskRequest) Reset() {
	*x = UpsertTaskRequest{}
	mi := &file_task_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTaskRequest) ProtoMessage() {}

func (x *UpsertTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTaskRequest.ProtoReflect.Descriptor instead.
func (*UpsertTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertTaskRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *UpsertTaskRequest) GetSolution() string {
	if x != nil && x.Solution != nil {
		return *x.Solution
	}
	return ""
}

func (x *UpsertTaskRequest) GetTestcases() []*TestCase {
	if x != nil {
		return x.Testcases
	}
	return nil
}

func (x *UpsertTaskRequest) GetAllowedRunnerIds() []string {
	if x != nil {
		return x.AllowedRunnerIds
	}
	return nil
}

func (x *UpsertTaskRequest) GetCompareId() string {
	if x != nil && x.CompareId != nil {
		return *x.CompareId
	}
	return ""
}

func (x *UpsertTaskRequest) GetLimit() *Limit {
	if x != nil {
		return x.Limit
	}
	return nil
}

type UpsertTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTaskResponse) Reset() {
	*x = UpsertTaskResponse{}
	mi := &file_task_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTaskResponse) ProtoMessage() {}

func (x *UpsertTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTaskResponse.ProtoReflect.Descriptor instead.
func (*UpsertTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_task_v1_messages_proto protoreflect.FileDescriptor

const file_task_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x16task/v1/messages.proto\x12\atask.v1\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x0fGetTasksRequest\x12)\n" +
	"\x10include_solution\x18\x01 \x01(\bR\x0fincludeSolution\"N\n" +
	"\bTestCase\x12\x14\n" +
	"\x05order\x18\x01 \x01(\x05R\x05order\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\"\xfa\x01\n" +
	"\fTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bsolution\x18\x02 \x01(\tR\bsolution\x12/\n" +
	"\ttestcases\x18\x03 \x03(\v2\x11.task.v1.TestCaseR\ttestcases\x12,\n" +
	"\x12allowed_runner_ids\x18\x04 \x03(\tR\x10allowedRunnerIds\x12*\n" +
	"\x11compare_script_id\x18\x05 \x01(\tR\x0fcompareScriptId\x12)\n" +
	"\x05limit\x18\x06 \x01(\v2\x0e.task.v1.LimitH\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"?\n" +
	"\x10GetTasksResponse\x12+\n" +
	"\x05tasks\x18\x01 \x03(\v2\x15.task.v1.TaskResponseR\x05tasks\"\x82\x02\n" +
	"\x05Limit\x12\x19\n" +
	"\bcpu_time\x18\x01 \x01(\x02R\acpuTime\x12$\n" +
	"\x0ecpu_extra_time\x18\x02 \x01(\x02R\fcpuExtraTime\x12\x1b\n" +
	"\twall_time\x18\x03 \x01(\x02R\bwallTime\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\x05R\x06memory\x12\x14\n" +
	"\x05stack\x18\x05 \x01(\x05R\x05stack\x12$\n" +
	"\x0emax_open_files\x18\x06 \x01(\x05R\fmaxOpenFiles\x12\"\n" +
	"\rmax_file_size\x18\a \x01(\x02R\vmaxFileSize\x12#\n" +
	"\rnetwork_allow\x18\b \x01(\bR\fnetworkAllow\"\xa4\x02\n" +
	"\x11UpsertTaskRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1f\n" +
	"\bsolution\x18\x02 \x01(\tH\x01R\bsolution\x88\x01\x01\x12/\n" +
	"\ttestcases\x18\x03 \x03(\v2\x11.task.v1.TestCaseR\ttestcases\x12,\n" +
	"\x12allowed_runner_ids\x18\x04 \x03(\tR\x10allowedRunnerIds\x12\"\n" +
	"\n" +
	"compare_id\x18\x05 \x01(\tH\x02R\tcompareId\x88\x01\x01\x12)\n" +
	"\x05limit\x18\x06 \x01(\v2\x0e.task.v1.LimitH\x03R\x05limit\x88\x01\x01B\x05\n" +
	"\x03_idB\v\n" +
	"\t_solutionB\r\n" +
	"\v_compare_idB\b\n" +
	"\x06_limit\"$\n" +
	"\x12UpsertTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB\x89\x01\n" +
	"\vcom.task.v1B\rMessagesProtoP\x01Z.github.com/CSKU-Lab/config-server/grpc/task/v1\xa2\x02\x03TXX\xaa\x02\aTask.V1\xca\x02\aTask\\V1\xe2\x02\x13Task\\V1\\GPBMetadata\xea\x02\bTask::V1b\x06proto3"

var (
	file_task_v1_messages_proto_rawDescOnce sync.Once
	file_task_v1_messages_proto_rawDescData []byte
)

func file_task_v1_messages_proto_rawDescGZIP() []byte {
	file_task_v1_messages_proto_rawDescOnce.Do(func() {
		file_task_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_v1_messages_proto_rawDesc), len(file_task_v1_messages_proto_rawDesc)))
	})
	return file_task_v1_messages_proto_rawDescData
}

var file_task_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_task_v1_messages_proto_goTypes = []any{
	(*GetTaskRequest)(nil),     // 0: task.v1.GetTaskRequest
	(*GetTasksRequest)(nil),    // 1: task.v1.GetTasksRequest
	(*TestCase)(nil),           // 2: task.v1.TestCase
	(*TaskResponse)(nil),       // 3: task.v1.TaskResponse
	(*GetTasksResponse)(nil),   // 4: task.v1.GetTasksResponse
	(*Limit)(nil),              // 5: task.v1.Limit
	(*UpsertTaskRequest)(nil),  // 6: task.v1.UpsertTaskRequest
	(*UpsertTaskResponse)(nil), // 7: task.v1.UpsertTaskResponse
	(*DeleteTaskRequest)(nil),  // 8: task.v1.DeleteTaskRequest
}
var file_task_v1_messages_proto_depIdxs = []int32{
	2, // 0: task.v1.TaskResponse.testcases:type_name -> task.v1.TestCase
	5, // 1: task.v1.TaskResponse.limit:type_name -> task.v1.Limit
	3, // 2: task.v1.GetTasksResponse.tasks:type_name -> task.v1.TaskResponse
	2, // 3: task.v1.UpsertTaskRequest.testcases:type_name -> task.v1.TestCase
	5, // 4: task.v1.UpsertTaskRequest.limit:type_name -> task.v1.Limit
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_task_v1_messages_proto_init() }
func file_task_v1_messages_proto_init() {
	if File_task_v1_messages_proto != nil {
		return
	}
	file_task_v1_messages_proto_msgTypes[3].OneofWrappers = []any{}
	file_task_v1_messages_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_v1_messages_proto_rawDesc), len(file_task_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_v1_messages_proto_goTypes,
		DependencyIndexes: file_task_v1_messages_proto_depIdxs,
		MessageInfos:      file_task_v1_messages_proto_msgTypes,
	}.Build()
	File_task_v1_messages_proto = out.File
	file_task_v1_messages_proto_goTypes = nil
	file_task_v1_messages_proto_depIdxs = nil
}
