// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: task/v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTasksRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeSolution bool                   `protobuf:"varint,1,opt,name=include_solution,json=includeSolution,proto3" json:"include_solution,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	mi := &file_task_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetTasksRequest) GetIncludeSolution() bool {
	if x != nil {
		return x.IncludeSolution
	}
	return false
}

type TestCaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCaseResponse) Reset() {
	*x = TestCaseResponse{}
	mi := &file_task_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCaseResponse) ProtoMessage() {}

func (x *TestCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCaseResponse.ProtoReflect.Descriptor instead.
func (*TestCaseResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *TestCaseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCaseResponse) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TestCaseResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Solution      string                 `protobuf:"bytes,2,opt,name=solution,proto3" json:"solution,omitempty"`
	Testcases     []*TestCaseResponse    `protobuf:"bytes,3,rep,name=testcases,proto3" json:"testcases,omitempty"`
	RunnerId      string                 `protobuf:"bytes,4,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	CompareId     string                 `protobuf:"bytes,5,opt,name=compare_id,json=compareId,proto3" json:"compare_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_task_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskResponse) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *TaskResponse) GetTestcases() []*TestCaseResponse {
	if x != nil {
		return x.Testcases
	}
	return nil
}

func (x *TaskResponse) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *TaskResponse) GetCompareId() string {
	if x != nil {
		return x.CompareId
	}
	return ""
}

type GetTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskResponse        `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	mi := &file_task_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetTasksResponse) GetTasks() []*TaskResponse {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type UpsertTestCase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTestCase) Reset() {
	*x = UpsertTestCase{}
	mi := &file_task_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTestCase) ProtoMessage() {}

func (x *UpsertTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTestCase.ProtoReflect.Descriptor instead.
func (*UpsertTestCase) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertTestCase) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *UpsertTestCase) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type SetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Solution      *string                `protobuf:"bytes,2,opt,name=solution,proto3,oneof" json:"solution,omitempty"`
	Testcases     []*UpsertTestCase      `protobuf:"bytes,3,rep,name=testcases,proto3" json:"testcases,omitempty"`
	RunnerId      *string                `protobuf:"bytes,4,opt,name=runner_id,json=runnerId,proto3,oneof" json:"runner_id,omitempty"`
	CompareId     *string                `protobuf:"bytes,5,opt,name=compare_id,json=compareId,proto3,oneof" json:"compare_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskRequest) Reset() {
	*x = SetTaskRequest{}
	mi := &file_task_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskRequest) ProtoMessage() {}

func (x *SetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskRequest.ProtoReflect.Descriptor instead.
func (*SetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *SetTaskRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *SetTaskRequest) GetSolution() string {
	if x != nil && x.Solution != nil {
		return *x.Solution
	}
	return ""
}

func (x *SetTaskRequest) GetTestcases() []*UpsertTestCase {
	if x != nil {
		return x.Testcases
	}
	return nil
}

func (x *SetTaskRequest) GetRunnerId() string {
	if x != nil && x.RunnerId != nil {
		return *x.RunnerId
	}
	return ""
}

func (x *SetTaskRequest) GetCompareId() string {
	if x != nil && x.CompareId != nil {
		return *x.CompareId
	}
	return ""
}

type SetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskResponse) Reset() {
	*x = SetTaskResponse{}
	mi := &file_task_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskResponse) ProtoMessage() {}

func (x *SetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskResponse.ProtoReflect.Descriptor instead.
func (*SetTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *SetTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_task_v1_messages_proto protoreflect.FileDescriptor

const file_task_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x16task/v1/messages.proto\x12\atask.v1\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x0fGetTasksRequest\x12)\n" +
	"\x10include_solution\x18\x01 \x01(\bR\x0fincludeSolution\"P\n" +
	"\x10TestCaseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\"\xaf\x01\n" +
	"\fTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bsolution\x18\x02 \x01(\tR\bsolution\x127\n" +
	"\ttestcases\x18\x03 \x03(\v2\x19.task.v1.TestCaseResponseR\ttestcases\x12\x1b\n" +
	"\trunner_id\x18\x04 \x01(\tR\brunnerId\x12\x1d\n" +
	"\n" +
	"compare_id\x18\x05 \x01(\tR\tcompareId\"?\n" +
	"\x10GetTasksResponse\x12+\n" +
	"\x05tasks\x18\x01 \x03(\v2\x15.task.v1.TaskResponseR\x05tasks\">\n" +
	"\x0eUpsertTestCase\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\"\xf4\x01\n" +
	"\x0eSetTaskRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1f\n" +
	"\bsolution\x18\x02 \x01(\tH\x01R\bsolution\x88\x01\x01\x125\n" +
	"\ttestcases\x18\x03 \x03(\v2\x17.task.v1.UpsertTestCaseR\ttestcases\x12 \n" +
	"\trunner_id\x18\x04 \x01(\tH\x02R\brunnerId\x88\x01\x01\x12\"\n" +
	"\n" +
	"compare_id\x18\x05 \x01(\tH\x03R\tcompareId\x88\x01\x01B\x05\n" +
	"\x03_idB\v\n" +
	"\t_solutionB\f\n" +
	"\n" +
	"_runner_idB\r\n" +
	"\v_compare_id\"!\n" +
	"\x0fSetTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB\x89\x01\n" +
	"\vcom.task.v1B\rMessagesProtoP\x01Z.github.com/CSKU-Lab/config-server/grpc/task/v1\xa2\x02\x03TXX\xaa\x02\aTask.V1\xca\x02\aTask\\V1\xe2\x02\x13Task\\V1\\GPBMetadata\xea\x02\bTask::V1b\x06proto3"

var (
	file_task_v1_messages_proto_rawDescOnce sync.Once
	file_task_v1_messages_proto_rawDescData []byte
)

func file_task_v1_messages_proto_rawDescGZIP() []byte {
	file_task_v1_messages_proto_rawDescOnce.Do(func() {
		file_task_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_v1_messages_proto_rawDesc), len(file_task_v1_messages_proto_rawDesc)))
	})
	return file_task_v1_messages_proto_rawDescData
}

var file_task_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_task_v1_messages_proto_goTypes = []any{
	(*GetTaskRequest)(nil),    // 0: task.v1.GetTaskRequest
	(*GetTasksRequest)(nil),   // 1: task.v1.GetTasksRequest
	(*TestCaseResponse)(nil),  // 2: task.v1.TestCaseResponse
	(*TaskResponse)(nil),      // 3: task.v1.TaskResponse
	(*GetTasksResponse)(nil),  // 4: task.v1.GetTasksResponse
	(*UpsertTestCase)(nil),    // 5: task.v1.UpsertTestCase
	(*SetTaskRequest)(nil),    // 6: task.v1.SetTaskRequest
	(*SetTaskResponse)(nil),   // 7: task.v1.SetTaskResponse
	(*DeleteTaskRequest)(nil), // 8: task.v1.DeleteTaskRequest
}
var file_task_v1_messages_proto_depIdxs = []int32{
	2, // 0: task.v1.TaskResponse.testcases:type_name -> task.v1.TestCaseResponse
	3, // 1: task.v1.GetTasksResponse.tasks:type_name -> task.v1.TaskResponse
	5, // 2: task.v1.SetTaskRequest.testcases:type_name -> task.v1.UpsertTestCase
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_task_v1_messages_proto_init() }
func file_task_v1_messages_proto_init() {
	if File_task_v1_messages_proto != nil {
		return
	}
	file_task_v1_messages_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_v1_messages_proto_rawDesc), len(file_task_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_v1_messages_proto_goTypes,
		DependencyIndexes: file_task_v1_messages_proto_depIdxs,
		MessageInfos:      file_task_v1_messages_proto_msgTypes,
	}.Build()
	File_task_v1_messages_proto = out.File
	file_task_v1_messages_proto_goTypes = nil
	file_task_v1_messages_proto_depIdxs = nil
}
