// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: task/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_task_v1_service_proto protoreflect.FileDescriptor

const file_task_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15task/v1/service.proto\x12\atask.v1\x1a\x16task/v1/messages.proto\x1a\x1bgoogle/protobuf/empty.proto2\x92\x02\n" +
	"\vTaskService\x12?\n" +
	"\bGetTasks\x12\x18.task.v1.GetTasksRequest\x1a\x19.task.v1.GetTasksResponse\x129\n" +
	"\aGetTask\x12\x17.task.v1.GetTaskRequest\x1a\x15.task.v1.TaskResponse\x12E\n" +
	"\n" +
	"UpsertTask\x12\x1a.task.v1.UpsertTaskRequest\x1a\x1b.task.v1.UpsertTaskResponse\x12@\n" +
	"\n" +
	"DeleteTask\x12\x1a.task.v1.DeleteTaskRequest\x1a\x16.google.protobuf.EmptyB\x88\x01\n" +
	"\vcom.task.v1B\fServiceProtoP\x01Z.github.com/CSKU-Lab/config-server/grpc/task/v1\xa2\x02\x03TXX\xaa\x02\aTask.V1\xca\x02\aTask\\V1\xe2\x02\x13Task\\V1\\GPBMetadata\xea\x02\bTask::V1b\x06proto3"

var file_task_v1_service_proto_goTypes = []any{
	(*GetTasksRequest)(nil),    // 0: task.v1.GetTasksRequest
	(*GetTaskRequest)(nil),     // 1: task.v1.GetTaskRequest
	(*UpsertTaskRequest)(nil),  // 2: task.v1.UpsertTaskRequest
	(*DeleteTaskRequest)(nil),  // 3: task.v1.DeleteTaskRequest
	(*GetTasksResponse)(nil),   // 4: task.v1.GetTasksResponse
	(*TaskResponse)(nil),       // 5: task.v1.TaskResponse
	(*UpsertTaskResponse)(nil), // 6: task.v1.UpsertTaskResponse
	(*emptypb.Empty)(nil),      // 7: google.protobuf.Empty
}
var file_task_v1_service_proto_depIdxs = []int32{
	0, // 0: task.v1.TaskService.GetTasks:input_type -> task.v1.GetTasksRequest
	1, // 1: task.v1.TaskService.GetTask:input_type -> task.v1.GetTaskRequest
	2, // 2: task.v1.TaskService.UpsertTask:input_type -> task.v1.UpsertTaskRequest
	3, // 3: task.v1.TaskService.DeleteTask:input_type -> task.v1.DeleteTaskRequest
	4, // 4: task.v1.TaskService.GetTasks:output_type -> task.v1.GetTasksResponse
	5, // 5: task.v1.TaskService.GetTask:output_type -> task.v1.TaskResponse
	6, // 6: task.v1.TaskService.UpsertTask:output_type -> task.v1.UpsertTaskResponse
	7, // 7: task.v1.TaskService.DeleteTask:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_task_v1_service_proto_init() }
func file_task_v1_service_proto_init() {
	if File_task_v1_service_proto != nil {
		return
	}
	file_task_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_v1_service_proto_rawDesc), len(file_task_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_v1_service_proto_goTypes,
		DependencyIndexes: file_task_v1_service_proto_depIdxs,
	}.Build()
	File_task_v1_service_proto = out.File
	file_task_v1_service_proto_goTypes = nil
	file_task_v1_service_proto_depIdxs = nil
}
