// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: task/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_task_v1_service_proto protoreflect.FileDescriptor

const file_task_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15task/v1/service.proto\x12\atask.v1\x1a\x16task/v1/messages.proto\x1a\x1bgoogle/protobuf/empty.proto2\x8e\x04\n" +
	"\vTaskService\x12?\n" +
	"\bGetTasks\x12\x18.task.v1.GetTasksRequest\x1a\x19.task.v1.GetTasksResponse\x129\n" +
	"\aGetTask\x12\x17.task.v1.GetTaskRequest\x1a\x15.task.v1.TaskResponse\x12A\n" +
	"\n" +
	"CreateTask\x12\x16.google.protobuf.Empty\x1a\x1b.task.v1.CreateTaskResponse\x12@\n" +
	"\n" +
	"UpdateTask\x12\x1a.task.v1.UpdateTaskRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"DeleteTask\x12\x1a.task.v1.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x15RemoveRunnerOnCascade\x12%.task.v1.RemoveRunnerOnCascadeRequest\x1a\x16.google.protobuf.Empty\x12d\n" +
	"\x1cRemoveCompareScriptOnCascade\x12,.task.v1.RemoveCompareScriptOnCascadeRequest\x1a\x16.google.protobuf.EmptyB/Z-github.com/CSKU-Lab/task-service/grpc/task/v1b\x06proto3"

var file_task_v1_service_proto_goTypes = []any{
	(*GetTasksRequest)(nil),                     // 0: task.v1.GetTasksRequest
	(*GetTaskRequest)(nil),                      // 1: task.v1.GetTaskRequest
	(*emptypb.Empty)(nil),                       // 2: google.protobuf.Empty
	(*UpdateTaskRequest)(nil),                   // 3: task.v1.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),                   // 4: task.v1.DeleteTaskRequest
	(*RemoveRunnerOnCascadeRequest)(nil),        // 5: task.v1.RemoveRunnerOnCascadeRequest
	(*RemoveCompareScriptOnCascadeRequest)(nil), // 6: task.v1.RemoveCompareScriptOnCascadeRequest
	(*GetTasksResponse)(nil),                    // 7: task.v1.GetTasksResponse
	(*TaskResponse)(nil),                        // 8: task.v1.TaskResponse
	(*CreateTaskResponse)(nil),                  // 9: task.v1.CreateTaskResponse
}
var file_task_v1_service_proto_depIdxs = []int32{
	0, // 0: task.v1.TaskService.GetTasks:input_type -> task.v1.GetTasksRequest
	1, // 1: task.v1.TaskService.GetTask:input_type -> task.v1.GetTaskRequest
	2, // 2: task.v1.TaskService.CreateTask:input_type -> google.protobuf.Empty
	3, // 3: task.v1.TaskService.UpdateTask:input_type -> task.v1.UpdateTaskRequest
	4, // 4: task.v1.TaskService.DeleteTask:input_type -> task.v1.DeleteTaskRequest
	5, // 5: task.v1.TaskService.RemoveRunnerOnCascade:input_type -> task.v1.RemoveRunnerOnCascadeRequest
	6, // 6: task.v1.TaskService.RemoveCompareScriptOnCascade:input_type -> task.v1.RemoveCompareScriptOnCascadeRequest
	7, // 7: task.v1.TaskService.GetTasks:output_type -> task.v1.GetTasksResponse
	8, // 8: task.v1.TaskService.GetTask:output_type -> task.v1.TaskResponse
	9, // 9: task.v1.TaskService.CreateTask:output_type -> task.v1.CreateTaskResponse
	2, // 10: task.v1.TaskService.UpdateTask:output_type -> google.protobuf.Empty
	2, // 11: task.v1.TaskService.DeleteTask:output_type -> google.protobuf.Empty
	2, // 12: task.v1.TaskService.RemoveRunnerOnCascade:output_type -> google.protobuf.Empty
	2, // 13: task.v1.TaskService.RemoveCompareScriptOnCascade:output_type -> google.protobuf.Empty
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_task_v1_service_proto_init() }
func file_task_v1_service_proto_init() {
	if File_task_v1_service_proto != nil {
		return
	}
	file_task_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_v1_service_proto_rawDesc), len(file_task_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_v1_service_proto_goTypes,
		DependencyIndexes: file_task_v1_service_proto_depIdxs,
	}.Build()
	File_task_v1_service_proto = out.File
	file_task_v1_service_proto_goTypes = nil
	file_task_v1_service_proto_depIdxs = nil
}
