// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: task/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Solution      string                 `protobuf:"bytes,2,opt,name=solution,proto3" json:"solution,omitempty"`
	Testcases     []*TestCase            `protobuf:"bytes,3,rep,name=testcases,proto3" json:"testcases,omitempty"`
	CompareId     string                 `protobuf:"bytes,4,opt,name=compare_id,json=compareId,proto3" json:"compare_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *Task) GetTestcases() []*TestCase {
	if x != nil {
		return x.Testcases
	}
	return nil
}

func (x *Task) GetCompareId() string {
	if x != nil {
		return x.CompareId
	}
	return ""
}

type TestCase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCase) Reset() {
	*x = TestCase{}
	mi := &file_task_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCase) ProtoMessage() {}

func (x *TestCase) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCase.ProtoReflect.Descriptor instead.
func (*TestCase) Descriptor() ([]byte, []int) {
	return file_task_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *TestCase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCase) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TestCase) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type GetTasksRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeSolution bool                   `protobuf:"varint,1,opt,name=include_solution,json=includeSolution,proto3" json:"include_solution,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	mi := &file_task_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTasksRequest) GetIncludeSolution() bool {
	if x != nil {
		return x.IncludeSolution
	}
	return false
}

type GetTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	mi := &file_task_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Testcases     []*TestCase            `protobuf:"bytes,2,rep,name=testcases,proto3" json:"testcases,omitempty"`
	Solution      string                 `protobuf:"bytes,3,opt,name=solution,proto3" json:"solution,omitempty"`
	CompareId     string                 `protobuf:"bytes,4,opt,name=compare_id,json=compareId,proto3" json:"compare_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTaskRequest) Reset() {
	*x = AddTaskRequest{}
	mi := &file_task_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskRequest) ProtoMessage() {}

func (x *AddTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskRequest.ProtoReflect.Descriptor instead.
func (*AddTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *AddTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddTaskRequest) GetTestcases() []*TestCase {
	if x != nil {
		return x.Testcases
	}
	return nil
}

func (x *AddTaskRequest) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *AddTaskRequest) GetCompareId() string {
	if x != nil {
		return x.CompareId
	}
	return ""
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Solution      *string                `protobuf:"bytes,2,opt,name=solution,proto3,oneof" json:"solution,omitempty"`
	Testcases     []*TestCase            `protobuf:"bytes,3,rep,name=testcases,proto3" json:"testcases,omitempty"`
	CompareId     *string                `protobuf:"bytes,4,opt,name=compare_id,json=compareId,proto3,oneof" json:"compare_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_task_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetSolution() string {
	if x != nil && x.Solution != nil {
		return *x.Solution
	}
	return ""
}

func (x *UpdateTaskRequest) GetTestcases() []*TestCase {
	if x != nil {
		return x.Testcases
	}
	return nil
}

func (x *UpdateTaskRequest) GetCompareId() string {
	if x != nil && x.CompareId != nil {
		return *x.CompareId
	}
	return ""
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_task_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_service_proto_rawDescGZIP(), []int{8}
}

var File_task_v1_service_proto protoreflect.FileDescriptor

const file_task_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15task/v1/service.proto\x12\atask.v1\"\x82\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bsolution\x18\x02 \x01(\tR\bsolution\x12/\n" +
	"\ttestcases\x18\x03 \x03(\v2\x11.task.v1.TestCaseR\ttestcases\x12\x1d\n" +
	"\n" +
	"compare_id\x18\x04 \x01(\tR\tcompareId\"H\n" +
	"\bTestCase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\"<\n" +
	"\x0fGetTasksRequest\x12)\n" +
	"\x10include_solution\x18\x01 \x01(\bR\x0fincludeSolution\"7\n" +
	"\x10GetTasksResponse\x12#\n" +
	"\x05tasks\x18\x01 \x03(\v2\r.task.v1.TaskR\x05tasks\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8c\x01\n" +
	"\x0eAddTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\ttestcases\x18\x02 \x03(\v2\x11.task.v1.TestCaseR\ttestcases\x12\x1a\n" +
	"\bsolution\x18\x03 \x01(\tR\bsolution\x12\x1d\n" +
	"\n" +
	"compare_id\x18\x04 \x01(\tR\tcompareId\"\xb5\x01\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\bsolution\x18\x02 \x01(\tH\x00R\bsolution\x88\x01\x01\x12/\n" +
	"\ttestcases\x18\x03 \x03(\v2\x11.task.v1.TestCaseR\ttestcases\x12\"\n" +
	"\n" +
	"compare_id\x18\x04 \x01(\tH\x01R\tcompareId\x88\x01\x01B\v\n" +
	"\t_solutionB\r\n" +
	"\v_compare_id\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteTaskResponse2\xb4\x02\n" +
	"\vTaskService\x12?\n" +
	"\bGetTasks\x12\x18.task.v1.GetTasksRequest\x1a\x19.task.v1.GetTasksResponse\x121\n" +
	"\aGetTask\x12\x17.task.v1.GetTaskRequest\x1a\r.task.v1.Task\x121\n" +
	"\aAddTask\x12\x17.task.v1.AddTaskRequest\x1a\r.task.v1.Task\x127\n" +
	"\n" +
	"UpdateTask\x12\x1a.task.v1.UpdateTaskRequest\x1a\r.task.v1.Task\x12E\n" +
	"\n" +
	"DeleteTask\x12\x1a.task.v1.DeleteTaskRequest\x1a\x1b.task.v1.DeleteTaskResponseB\x88\x01\n" +
	"\vcom.task.v1B\fServiceProtoP\x01Z.github.com/CSKU-Lab/config-server/grpc/task/v1\xa2\x02\x03TXX\xaa\x02\aTask.V1\xca\x02\aTask\\V1\xe2\x02\x13Task\\V1\\GPBMetadata\xea\x02\bTask::V1b\x06proto3"

var (
	file_task_v1_service_proto_rawDescOnce sync.Once
	file_task_v1_service_proto_rawDescData []byte
)

func file_task_v1_service_proto_rawDescGZIP() []byte {
	file_task_v1_service_proto_rawDescOnce.Do(func() {
		file_task_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_v1_service_proto_rawDesc), len(file_task_v1_service_proto_rawDesc)))
	})
	return file_task_v1_service_proto_rawDescData
}

var file_task_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_task_v1_service_proto_goTypes = []any{
	(*Task)(nil),               // 0: task.v1.Task
	(*TestCase)(nil),           // 1: task.v1.TestCase
	(*GetTasksRequest)(nil),    // 2: task.v1.GetTasksRequest
	(*GetTasksResponse)(nil),   // 3: task.v1.GetTasksResponse
	(*GetTaskRequest)(nil),     // 4: task.v1.GetTaskRequest
	(*AddTaskRequest)(nil),     // 5: task.v1.AddTaskRequest
	(*UpdateTaskRequest)(nil),  // 6: task.v1.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),  // 7: task.v1.DeleteTaskRequest
	(*DeleteTaskResponse)(nil), // 8: task.v1.DeleteTaskResponse
}
var file_task_v1_service_proto_depIdxs = []int32{
	1, // 0: task.v1.Task.testcases:type_name -> task.v1.TestCase
	0, // 1: task.v1.GetTasksResponse.tasks:type_name -> task.v1.Task
	1, // 2: task.v1.AddTaskRequest.testcases:type_name -> task.v1.TestCase
	1, // 3: task.v1.UpdateTaskRequest.testcases:type_name -> task.v1.TestCase
	2, // 4: task.v1.TaskService.GetTasks:input_type -> task.v1.GetTasksRequest
	4, // 5: task.v1.TaskService.GetTask:input_type -> task.v1.GetTaskRequest
	5, // 6: task.v1.TaskService.AddTask:input_type -> task.v1.AddTaskRequest
	6, // 7: task.v1.TaskService.UpdateTask:input_type -> task.v1.UpdateTaskRequest
	7, // 8: task.v1.TaskService.DeleteTask:input_type -> task.v1.DeleteTaskRequest
	3, // 9: task.v1.TaskService.GetTasks:output_type -> task.v1.GetTasksResponse
	0, // 10: task.v1.TaskService.GetTask:output_type -> task.v1.Task
	0, // 11: task.v1.TaskService.AddTask:output_type -> task.v1.Task
	0, // 12: task.v1.TaskService.UpdateTask:output_type -> task.v1.Task
	8, // 13: task.v1.TaskService.DeleteTask:output_type -> task.v1.DeleteTaskResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_task_v1_service_proto_init() }
func file_task_v1_service_proto_init() {
	if File_task_v1_service_proto != nil {
		return
	}
	file_task_v1_service_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_v1_service_proto_rawDesc), len(file_task_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_v1_service_proto_goTypes,
		DependencyIndexes: file_task_v1_service_proto_depIdxs,
		MessageInfos:      file_task_v1_service_proto_msgTypes,
	}.Build()
	File_task_v1_service_proto = out.File
	file_task_v1_service_proto_goTypes = nil
	file_task_v1_service_proto_depIdxs = nil
}
