services:
  app:
    container_name: task-grpc
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8082"
    volumes:
      - .:/app
    environment:
      - ENV=docker
    env_file:
      - .env
    restart: unless-stopped
  mongo:
    container_name: task-mongodb
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: task-server
      MONGO_INITDB_ROOT_PASSWORD: task-server-password
    restart: unless-stopped

  redis:
    container_name: task-redis
    image: redis:7.4.3
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  mongo_data:
  redis-data:
