services:
  mongo:
    container_name: task-mongodb
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: task-server
      MONGO_INITDB_ROOT_PASSWORD: task-server-password
    restart: unless-stopped

  redis:
    container_name: task-redis
    image: redis:7.4.3
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  mongo_data:
  redis-data:
