// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: grader/v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionStatus int32

const (
	ExecutionStatus_STATUS_UNSPECIFIED           ExecutionStatus = 0
	ExecutionStatus_STATUS_COMPILE_FAILED        ExecutionStatus = 1
	ExecutionStatus_STATUS_RUN_PASSED            ExecutionStatus = 2
	ExecutionStatus_STATUS_RUN_FAILED            ExecutionStatus = 3
	ExecutionStatus_STATUS_TIME_LIMIT_EXCEEDED   ExecutionStatus = 4
	ExecutionStatus_STATUS_MEMORY_LIMIT_EXCEEDED ExecutionStatus = 5
	ExecutionStatus_STATUS_RUNTIME_ERROR         ExecutionStatus = 6
	ExecutionStatus_STATUS_SIGNAL_ERROR          ExecutionStatus = 7
	ExecutionStatus_STATUS_GRADER_ERROR          ExecutionStatus = 8
	ExecutionStatus_STATUS_QUEUED                ExecutionStatus = 9
	ExecutionStatus_STATUS_RUNNING               ExecutionStatus = 10
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0:  "STATUS_UNSPECIFIED",
		1:  "STATUS_COMPILE_FAILED",
		2:  "STATUS_RUN_PASSED",
		3:  "STATUS_RUN_FAILED",
		4:  "STATUS_TIME_LIMIT_EXCEEDED",
		5:  "STATUS_MEMORY_LIMIT_EXCEEDED",
		6:  "STATUS_RUNTIME_ERROR",
		7:  "STATUS_SIGNAL_ERROR",
		8:  "STATUS_GRADER_ERROR",
		9:  "STATUS_QUEUED",
		10: "STATUS_RUNNING",
	}
	ExecutionStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED":           0,
		"STATUS_COMPILE_FAILED":        1,
		"STATUS_RUN_PASSED":            2,
		"STATUS_RUN_FAILED":            3,
		"STATUS_TIME_LIMIT_EXCEEDED":   4,
		"STATUS_MEMORY_LIMIT_EXCEEDED": 5,
		"STATUS_RUNTIME_ERROR":         6,
		"STATUS_SIGNAL_ERROR":          7,
		"STATUS_GRADER_ERROR":          8,
		"STATUS_QUEUED":                9,
		"STATUS_RUNNING":               10,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_grader_v1_messages_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_grader_v1_messages_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{0}
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_grader_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Limit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuTime       float32                `protobuf:"fixed32,1,opt,name=cpu_time,json=cpuTime,proto3" json:"cpu_time,omitempty"`
	CpuExtraTime  float32                `protobuf:"fixed32,2,opt,name=cpu_extra_time,json=cpuExtraTime,proto3" json:"cpu_extra_time,omitempty"`
	WallTime      float32                `protobuf:"fixed32,3,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	Memory        int32                  `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Stack         int32                  `protobuf:"varint,5,opt,name=stack,proto3" json:"stack,omitempty"`
	MaxOpenFiles  int32                  `protobuf:"varint,6,opt,name=max_open_files,json=maxOpenFiles,proto3" json:"max_open_files,omitempty"`
	MaxFileSize   float32                `protobuf:"fixed32,7,opt,name=max_file_size,json=maxFileSize,proto3" json:"max_file_size,omitempty"`
	NetworkAllow  bool                   `protobuf:"varint,8,opt,name=network_allow,json=networkAllow,proto3" json:"network_allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limit) Reset() {
	*x = Limit{}
	mi := &file_grader_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limit) ProtoMessage() {}

func (x *Limit) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limit.ProtoReflect.Descriptor instead.
func (*Limit) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Limit) GetCpuTime() float32 {
	if x != nil {
		return x.CpuTime
	}
	return 0
}

func (x *Limit) GetCpuExtraTime() float32 {
	if x != nil {
		return x.CpuExtraTime
	}
	return 0
}

func (x *Limit) GetWallTime() float32 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *Limit) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Limit) GetStack() int32 {
	if x != nil {
		return x.Stack
	}
	return 0
}

func (x *Limit) GetMaxOpenFiles() int32 {
	if x != nil {
		return x.MaxOpenFiles
	}
	return 0
}

func (x *Limit) GetMaxFileSize() float32 {
	if x != nil {
		return x.MaxFileSize
	}
	return 0
}

func (x *Limit) GetNetworkAllow() bool {
	if x != nil {
		return x.NetworkAllow
	}
	return false
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	RunnerId      string                 `protobuf:"bytes,2,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Limit         *Limit                 `protobuf:"bytes,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_grader_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *RunRequest) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *RunRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *RunRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *RunRequest) GetLimit() *Limit {
	if x != nil {
		return x.Limit
	}
	return nil
}

type RunResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=grader.v1.ExecutionStatus" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	WallTime      float32                `protobuf:"fixed32,4,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	Memory        int32                  `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResultResponse) Reset() {
	*x = RunResultResponse{}
	mi := &file_grader_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResultResponse) ProtoMessage() {}

func (x *RunResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResultResponse.ProtoReflect.Descriptor instead.
func (*RunResultResponse) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RunResultResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *RunResultResponse) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_STATUS_UNSPECIFIED
}

func (x *RunResultResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RunResultResponse) GetWallTime() float32 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *RunResultResponse) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

type TestCaseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=grader.v1.ExecutionStatus" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	WallTime      float32                `protobuf:"fixed32,5,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	Memory        int32                  `protobuf:"varint,6,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCaseResult) Reset() {
	*x = TestCaseResult{}
	mi := &file_grader_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCaseResult) ProtoMessage() {}

func (x *TestCaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCaseResult.ProtoReflect.Descriptor instead.
func (*TestCaseResult) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *TestCaseResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCaseResult) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_STATUS_UNSPECIFIED
}

func (x *TestCaseResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TestCaseResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestCaseResult) GetWallTime() float32 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *TestCaseResult) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

type GradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RunnerId      string                 `protobuf:"bytes,3,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeRequest) Reset() {
	*x = GradeRequest{}
	mi := &file_grader_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeRequest) ProtoMessage() {}

func (x *GradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeRequest.ProtoReflect.Descriptor instead.
func (*GradeRequest) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GradeRequest) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GradeRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GradeRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

type TestCaseGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TestCases     []*TestCaseResult      `protobuf:"bytes,2,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCaseGroup) Reset() {
	*x = TestCaseGroup{}
	mi := &file_grader_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCaseGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCaseGroup) ProtoMessage() {}

func (x *TestCaseGroup) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCaseGroup.ProtoReflect.Descriptor instead.
func (*TestCaseGroup) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *TestCaseGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCaseGroup) GetTestCases() []*TestCaseResult {
	if x != nil {
		return x.TestCases
	}
	return nil
}

func (x *TestCaseGroup) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GradeResultResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId    string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status         ExecutionStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=grader.v1.ExecutionStatus" json:"status,omitempty"`
	TestCaseGroups []*TestCaseGroup       `protobuf:"bytes,3,rep,name=test_case_groups,json=testCaseGroups,proto3" json:"test_case_groups,omitempty"`
	AvgWallTime    float32                `protobuf:"fixed32,4,opt,name=avg_wall_time,json=avgWallTime,proto3" json:"avg_wall_time,omitempty"`
	AvgMemory      int32                  `protobuf:"varint,5,opt,name=avg_memory,json=avgMemory,proto3" json:"avg_memory,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GradeResultResponse) Reset() {
	*x = GradeResultResponse{}
	mi := &file_grader_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeResultResponse) ProtoMessage() {}

func (x *GradeResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeResultResponse.ProtoReflect.Descriptor instead.
func (*GradeResultResponse) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GradeResultResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GradeResultResponse) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_STATUS_UNSPECIFIED
}

func (x *GradeResultResponse) GetTestCaseGroups() []*TestCaseGroup {
	if x != nil {
		return x.TestCaseGroups
	}
	return nil
}

func (x *GradeResultResponse) GetAvgWallTime() float32 {
	if x != nil {
		return x.AvgWallTime
	}
	return 0
}

func (x *GradeResultResponse) GetAvgMemory() int32 {
	if x != nil {
		return x.AvgMemory
	}
	return 0
}

type TestCaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Order         int32                  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCaseRequest) Reset() {
	*x = TestCaseRequest{}
	mi := &file_grader_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCaseRequest) ProtoMessage() {}

func (x *TestCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCaseRequest.ProtoReflect.Descriptor instead.
func (*TestCaseRequest) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *TestCaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCaseRequest) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *TestCaseRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type GenerateTestCasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	RunnerId      string                 `protobuf:"bytes,2,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Testcases     []*TestCaseRequest     `protobuf:"bytes,3,rep,name=testcases,proto3" json:"testcases,omitempty"`
	Limit         *Limit                 `protobuf:"bytes,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTestCasesRequest) Reset() {
	*x = GenerateTestCasesRequest{}
	mi := &file_grader_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTestCasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTestCasesRequest) ProtoMessage() {}

func (x *GenerateTestCasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTestCasesRequest.ProtoReflect.Descriptor instead.
func (*GenerateTestCasesRequest) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateTestCasesRequest) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GenerateTestCasesRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *GenerateTestCasesRequest) GetTestcases() []*TestCaseRequest {
	if x != nil {
		return x.Testcases
	}
	return nil
}

func (x *GenerateTestCasesRequest) GetLimit() *Limit {
	if x != nil {
		return x.Limit
	}
	return nil
}

type TestCaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Order         int32                  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCaseResponse) Reset() {
	*x = TestCaseResponse{}
	mi := &file_grader_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCaseResponse) ProtoMessage() {}

func (x *TestCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCaseResponse.ProtoReflect.Descriptor instead.
func (*TestCaseResponse) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *TestCaseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCaseResponse) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *TestCaseResponse) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TestCaseResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type GenerateTestCasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TestCaseResponse    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTestCasesResponse) Reset() {
	*x = GenerateTestCasesResponse{}
	mi := &file_grader_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTestCasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTestCasesResponse) ProtoMessage() {}

func (x *GenerateTestCasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTestCasesResponse.ProtoReflect.Descriptor instead.
func (*GenerateTestCasesResponse) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateTestCasesResponse) GetResults() []*TestCaseResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_grader_v1_messages_proto protoreflect.FileDescriptor

const file_grader_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x18grader/v1/messages.proto\x12\tgrader.v1\"4\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x82\x02\n" +
	"\x05Limit\x12\x19\n" +
	"\bcpu_time\x18\x01 \x01(\x02R\acpuTime\x12$\n" +
	"\x0ecpu_extra_time\x18\x02 \x01(\x02R\fcpuExtraTime\x12\x1b\n" +
	"\twall_time\x18\x03 \x01(\x02R\bwallTime\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\x05R\x06memory\x12\x14\n" +
	"\x05stack\x18\x05 \x01(\x05R\x05stack\x12$\n" +
	"\x0emax_open_files\x18\x06 \x01(\x05R\fmaxOpenFiles\x12\"\n" +
	"\rmax_file_size\x18\a \x01(\x02R\vmaxFileSize\x12#\n" +
	"\rnetwork_allow\x18\b \x01(\bR\fnetworkAllow\"\x8e\x01\n" +
	"\n" +
	"RunRequest\x12%\n" +
	"\x05files\x18\x01 \x03(\v2\x0f.grader.v1.FileR\x05files\x12\x1b\n" +
	"\trunner_id\x18\x02 \x01(\tR\brunnerId\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\x12&\n" +
	"\x05limit\x18\x04 \x01(\v2\x10.grader.v1.LimitR\x05limit\"\xb7\x01\n" +
	"\x11RunResultResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.grader.v1.ExecutionStatusR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x1b\n" +
	"\twall_time\x18\x04 \x01(\x02R\bwallTime\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\x05R\x06memory\"\xbb\x01\n" +
	"\x0eTestCaseResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.grader.v1.ExecutionStatusR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1b\n" +
	"\twall_time\x18\x05 \x01(\x02R\bwallTime\x12\x16\n" +
	"\x06memory\x18\x06 \x01(\x05R\x06memory\"k\n" +
	"\fGradeRequest\x12%\n" +
	"\x05files\x18\x01 \x03(\v2\x0f.grader.v1.FileR\x05files\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1b\n" +
	"\trunner_id\x18\x03 \x01(\tR\brunnerId\"o\n" +
	"\rTestCaseGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\n" +
	"test_cases\x18\x02 \x03(\v2\x19.grader.v1.TestCaseResultR\ttestCases\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"\xf3\x01\n" +
	"\x13GradeResultResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.grader.v1.ExecutionStatusR\x06status\x12B\n" +
	"\x10test_case_groups\x18\x03 \x03(\v2\x18.grader.v1.TestCaseGroupR\x0etestCaseGroups\x12\"\n" +
	"\ravg_wall_time\x18\x04 \x01(\x02R\vavgWallTime\x12\x1d\n" +
	"\n" +
	"avg_memory\x18\x05 \x01(\x05R\tavgMemory\"M\n" +
	"\x0fTestCaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x05R\x05order\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\"\xc0\x01\n" +
	"\x18GenerateTestCasesRequest\x12%\n" +
	"\x05files\x18\x01 \x03(\v2\x0f.grader.v1.FileR\x05files\x12\x1b\n" +
	"\trunner_id\x18\x02 \x01(\tR\brunnerId\x128\n" +
	"\ttestcases\x18\x03 \x03(\v2\x1a.grader.v1.TestCaseRequestR\ttestcases\x12&\n" +
	"\x05limit\x18\x04 \x01(\v2\x10.grader.v1.LimitR\x05limit\"f\n" +
	"\x10TestCaseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x05R\x05order\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\"R\n" +
	"\x19GenerateTestCasesResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.grader.v1.TestCaseResponseR\aresults*\xa7\x02\n" +
	"\x0fExecutionStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15STATUS_COMPILE_FAILED\x10\x01\x12\x15\n" +
	"\x11STATUS_RUN_PASSED\x10\x02\x12\x15\n" +
	"\x11STATUS_RUN_FAILED\x10\x03\x12\x1e\n" +
	"\x1aSTATUS_TIME_LIMIT_EXCEEDED\x10\x04\x12 \n" +
	"\x1cSTATUS_MEMORY_LIMIT_EXCEEDED\x10\x05\x12\x18\n" +
	"\x14STATUS_RUNTIME_ERROR\x10\x06\x12\x17\n" +
	"\x13STATUS_SIGNAL_ERROR\x10\a\x12\x17\n" +
	"\x13STATUS_GRADER_ERROR\x10\b\x12\x11\n" +
	"\rSTATUS_QUEUED\x10\t\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\n" +
	"B\x95\x01\n" +
	"\rcom.grader.v1B\rMessagesProtoP\x01Z0github.com/CSKU-Lab/grader-server/grpc/grader/v1\xa2\x02\x03GXX\xaa\x02\tGrader.V1\xca\x02\tGrader\\V1\xe2\x02\x15Grader\\V1\\GPBMetadata\xea\x02\n" +
	"Grader::V1b\x06proto3"

var (
	file_grader_v1_messages_proto_rawDescOnce sync.Once
	file_grader_v1_messages_proto_rawDescData []byte
)

func file_grader_v1_messages_proto_rawDescGZIP() []byte {
	file_grader_v1_messages_proto_rawDescOnce.Do(func() {
		file_grader_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grader_v1_messages_proto_rawDesc), len(file_grader_v1_messages_proto_rawDesc)))
	})
	return file_grader_v1_messages_proto_rawDescData
}

var file_grader_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grader_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_grader_v1_messages_proto_goTypes = []any{
	(ExecutionStatus)(0),              // 0: grader.v1.ExecutionStatus
	(*File)(nil),                      // 1: grader.v1.File
	(*Limit)(nil),                     // 2: grader.v1.Limit
	(*RunRequest)(nil),                // 3: grader.v1.RunRequest
	(*RunResultResponse)(nil),         // 4: grader.v1.RunResultResponse
	(*TestCaseResult)(nil),            // 5: grader.v1.TestCaseResult
	(*GradeRequest)(nil),              // 6: grader.v1.GradeRequest
	(*TestCaseGroup)(nil),             // 7: grader.v1.TestCaseGroup
	(*GradeResultResponse)(nil),       // 8: grader.v1.GradeResultResponse
	(*TestCaseRequest)(nil),           // 9: grader.v1.TestCaseRequest
	(*GenerateTestCasesRequest)(nil),  // 10: grader.v1.GenerateTestCasesRequest
	(*TestCaseResponse)(nil),          // 11: grader.v1.TestCaseResponse
	(*GenerateTestCasesResponse)(nil), // 12: grader.v1.GenerateTestCasesResponse
}
var file_grader_v1_messages_proto_depIdxs = []int32{
	1,  // 0: grader.v1.RunRequest.files:type_name -> grader.v1.File
	2,  // 1: grader.v1.RunRequest.limit:type_name -> grader.v1.Limit
	0,  // 2: grader.v1.RunResultResponse.status:type_name -> grader.v1.ExecutionStatus
	0,  // 3: grader.v1.TestCaseResult.status:type_name -> grader.v1.ExecutionStatus
	1,  // 4: grader.v1.GradeRequest.files:type_name -> grader.v1.File
	5,  // 5: grader.v1.TestCaseGroup.test_cases:type_name -> grader.v1.TestCaseResult
	0,  // 6: grader.v1.GradeResultResponse.status:type_name -> grader.v1.ExecutionStatus
	7,  // 7: grader.v1.GradeResultResponse.test_case_groups:type_name -> grader.v1.TestCaseGroup
	1,  // 8: grader.v1.GenerateTestCasesRequest.files:type_name -> grader.v1.File
	9,  // 9: grader.v1.GenerateTestCasesRequest.testcases:type_name -> grader.v1.TestCaseRequest
	2,  // 10: grader.v1.GenerateTestCasesRequest.limit:type_name -> grader.v1.Limit
	11, // 11: grader.v1.GenerateTestCasesResponse.results:type_name -> grader.v1.TestCaseResponse
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_grader_v1_messages_proto_init() }
func file_grader_v1_messages_proto_init() {
	if File_grader_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grader_v1_messages_proto_rawDesc), len(file_grader_v1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grader_v1_messages_proto_goTypes,
		DependencyIndexes: file_grader_v1_messages_proto_depIdxs,
		EnumInfos:         file_grader_v1_messages_proto_enumTypes,
		MessageInfos:      file_grader_v1_messages_proto_msgTypes,
	}.Build()
	File_grader_v1_messages_proto = out.File
	file_grader_v1_messages_proto_goTypes = nil
	file_grader_v1_messages_proto_depIdxs = nil
}
