// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: grader/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraderService_Run_FullMethodName               = "/grader.v1.GraderService/Run"
	GraderService_GetRunResult_FullMethodName      = "/grader.v1.GraderService/GetRunResult"
	GraderService_Grade_FullMethodName             = "/grader.v1.GraderService/Grade"
	GraderService_GetGradeResult_FullMethodName    = "/grader.v1.GraderService/GetGradeResult"
	GraderService_GenerateTestCases_FullMethodName = "/grader.v1.GraderService/GenerateTestCases"
)

// GraderServiceClient is the client API for GraderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraderServiceClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunResultResponse], error)
	GetRunResult(ctx context.Context, in *GetRunResultRequest, opts ...grpc.CallOption) (*RunResultResponse, error)
	Grade(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradedResponse, error)
	GetGradeResult(ctx context.Context, in *GetGradeResultRequest, opts ...grpc.CallOption) (*GradeResultResponse, error)
	GenerateTestCases(ctx context.Context, in *GenerateTestCasesRequest, opts ...grpc.CallOption) (*GenerateTestCasesResponse, error)
}

type graderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraderServiceClient(cc grpc.ClientConnInterface) GraderServiceClient {
	return &graderServiceClient{cc}
}

func (c *graderServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunResultResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GraderService_ServiceDesc.Streams[0], GraderService_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, RunResultResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraderService_RunClient = grpc.ServerStreamingClient[RunResultResponse]

func (c *graderServiceClient) GetRunResult(ctx context.Context, in *GetRunResultRequest, opts ...grpc.CallOption) (*RunResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResultResponse)
	err := c.cc.Invoke(ctx, GraderService_GetRunResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graderServiceClient) Grade(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradedResponse)
	err := c.cc.Invoke(ctx, GraderService_Grade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graderServiceClient) GetGradeResult(ctx context.Context, in *GetGradeResultRequest, opts ...grpc.CallOption) (*GradeResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeResultResponse)
	err := c.cc.Invoke(ctx, GraderService_GetGradeResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graderServiceClient) GenerateTestCases(ctx context.Context, in *GenerateTestCasesRequest, opts ...grpc.CallOption) (*GenerateTestCasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTestCasesResponse)
	err := c.cc.Invoke(ctx, GraderService_GenerateTestCases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraderServiceServer is the server API for GraderService service.
// All implementations must embed UnimplementedGraderServiceServer
// for forward compatibility.
type GraderServiceServer interface {
	Run(*RunRequest, grpc.ServerStreamingServer[RunResultResponse]) error
	GetRunResult(context.Context, *GetRunResultRequest) (*RunResultResponse, error)
	Grade(context.Context, *GradeRequest) (*GradedResponse, error)
	GetGradeResult(context.Context, *GetGradeResultRequest) (*GradeResultResponse, error)
	GenerateTestCases(context.Context, *GenerateTestCasesRequest) (*GenerateTestCasesResponse, error)
	mustEmbedUnimplementedGraderServiceServer()
}

// UnimplementedGraderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraderServiceServer struct{}

func (UnimplementedGraderServiceServer) Run(*RunRequest, grpc.ServerStreamingServer[RunResultResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedGraderServiceServer) GetRunResult(context.Context, *GetRunResultRequest) (*RunResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunResult not implemented")
}
func (UnimplementedGraderServiceServer) Grade(context.Context, *GradeRequest) (*GradedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Grade not implemented")
}
func (UnimplementedGraderServiceServer) GetGradeResult(context.Context, *GetGradeResultRequest) (*GradeResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGradeResult not implemented")
}
func (UnimplementedGraderServiceServer) GenerateTestCases(context.Context, *GenerateTestCasesRequest) (*GenerateTestCasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateTestCases not implemented")
}
func (UnimplementedGraderServiceServer) mustEmbedUnimplementedGraderServiceServer() {}
func (UnimplementedGraderServiceServer) testEmbeddedByValue()                       {}

// UnsafeGraderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraderServiceServer will
// result in compilation errors.
type UnsafeGraderServiceServer interface {
	mustEmbedUnimplementedGraderServiceServer()
}

func RegisterGraderServiceServer(s grpc.ServiceRegistrar, srv GraderServiceServer) {
	// If the following call pancis, it indicates UnimplementedGraderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraderService_ServiceDesc, srv)
}

func _GraderService_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GraderServiceServer).Run(m, &grpc.GenericServerStream[RunRequest, RunResultResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraderService_RunServer = grpc.ServerStreamingServer[RunResultResponse]

func _GraderService_GetRunResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderServiceServer).GetRunResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraderService_GetRunResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderServiceServer).GetRunResult(ctx, req.(*GetRunResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraderService_Grade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderServiceServer).Grade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraderService_Grade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderServiceServer).Grade(ctx, req.(*GradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraderService_GetGradeResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGradeResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderServiceServer).GetGradeResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraderService_GetGradeResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderServiceServer).GetGradeResult(ctx, req.(*GetGradeResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraderService_GenerateTestCases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTestCasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderServiceServer).GenerateTestCases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraderService_GenerateTestCases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderServiceServer).GenerateTestCases(ctx, req.(*GenerateTestCasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraderService_ServiceDesc is the grpc.ServiceDesc for GraderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grader.v1.GraderService",
	HandlerType: (*GraderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRunResult",
			Handler:    _GraderService_GetRunResult_Handler,
		},
		{
			MethodName: "Grade",
			Handler:    _GraderService_Grade_Handler,
		},
		{
			MethodName: "GetGradeResult",
			Handler:    _GraderService_GetGradeResult_Handler,
		},
		{
			MethodName: "GenerateTestCases",
			Handler:    _GraderService_GenerateTestCases_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _GraderService_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grader/v1/service.proto",
}
