// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: config/v1/runners.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunnerPaginationData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BuildScript   string                 `protobuf:"bytes,3,opt,name=build_script,json=buildScript,proto3" json:"build_script,omitempty"`
	RunScript     string                 `protobuf:"bytes,4,opt,name=run_script,json=runScript,proto3" json:"run_script,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	InitialFiles  []*File                `protobuf:"bytes,6,rep,name=initial_files,json=initialFiles,proto3" json:"initial_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerPaginationData) Reset() {
	*x = RunnerPaginationData{}
	mi := &file_config_v1_runners_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerPaginationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerPaginationData) ProtoMessage() {}

func (x *RunnerPaginationData) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerPaginationData.ProtoReflect.Descriptor instead.
func (*RunnerPaginationData) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{0}
}

func (x *RunnerPaginationData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunnerPaginationData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RunnerPaginationData) GetBuildScript() string {
	if x != nil {
		return x.BuildScript
	}
	return ""
}

func (x *RunnerPaginationData) GetRunScript() string {
	if x != nil {
		return x.RunScript
	}
	return ""
}

func (x *RunnerPaginationData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RunnerPaginationData) GetInitialFiles() []*File {
	if x != nil {
		return x.InitialFiles
	}
	return nil
}

type GetRunnersPaginationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pagination     *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	IncludeScripts bool                   `protobuf:"varint,2,opt,name=include_scripts,json=includeScripts,proto3" json:"include_scripts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRunnersPaginationRequest) Reset() {
	*x = GetRunnersPaginationRequest{}
	mi := &file_config_v1_runners_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunnersPaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnersPaginationRequest) ProtoMessage() {}

func (x *GetRunnersPaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnersPaginationRequest.ProtoReflect.Descriptor instead.
func (*GetRunnersPaginationRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{1}
}

func (x *GetRunnersPaginationRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetRunnersPaginationRequest) GetIncludeScripts() bool {
	if x != nil {
		return x.IncludeScripts
	}
	return false
}

type GetRunnersPaginationResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Runners       []*RunnerPaginationData `protobuf:"bytes,1,rep,name=runners,proto3" json:"runners,omitempty"`
	Count         int32                   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunnersPaginationResponse) Reset() {
	*x = GetRunnersPaginationResponse{}
	mi := &file_config_v1_runners_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunnersPaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnersPaginationResponse) ProtoMessage() {}

func (x *GetRunnersPaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnersPaginationResponse.ProtoReflect.Descriptor instead.
func (*GetRunnersPaginationResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{2}
}

func (x *GetRunnersPaginationResponse) GetRunners() []*RunnerPaginationData {
	if x != nil {
		return x.Runners
	}
	return nil
}

func (x *GetRunnersPaginationResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunnerRequest) Reset() {
	*x = GetRunnerRequest{}
	mi := &file_config_v1_runners_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnerRequest) ProtoMessage() {}

func (x *GetRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnerRequest.ProtoReflect.Descriptor instead.
func (*GetRunnerRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{3}
}

func (x *GetRunnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllRunnersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeMetadata bool                   `protobuf:"varint,1,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	IncludeScripts  bool                   `protobuf:"varint,2,opt,name=include_scripts,json=includeScripts,proto3" json:"include_scripts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAllRunnersRequest) Reset() {
	*x = GetAllRunnersRequest{}
	mi := &file_config_v1_runners_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRunnersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRunnersRequest) ProtoMessage() {}

func (x *GetAllRunnersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRunnersRequest.ProtoReflect.Descriptor instead.
func (*GetAllRunnersRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllRunnersRequest) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

func (x *GetAllRunnersRequest) GetIncludeScripts() bool {
	if x != nil {
		return x.IncludeScripts
	}
	return false
}

type GetAllRunnersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runners       []*RunnerResponse      `protobuf:"bytes,1,rep,name=runners,proto3" json:"runners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRunnersResponse) Reset() {
	*x = GetAllRunnersResponse{}
	mi := &file_config_v1_runners_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRunnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRunnersResponse) ProtoMessage() {}

func (x *GetAllRunnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRunnersResponse.ProtoReflect.Descriptor instead.
func (*GetAllRunnersResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllRunnersResponse) GetRunners() []*RunnerResponse {
	if x != nil {
		return x.Runners
	}
	return nil
}

type RunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BuildScript   string                 `protobuf:"bytes,3,opt,name=build_script,json=buildScript,proto3" json:"build_script,omitempty"`
	RunScript     string                 `protobuf:"bytes,4,opt,name=run_script,json=runScript,proto3" json:"run_script,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	InitialFiles  []*File                `protobuf:"bytes,6,rep,name=initial_files,json=initialFiles,proto3" json:"initial_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerResponse) Reset() {
	*x = RunnerResponse{}
	mi := &file_config_v1_runners_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerResponse) ProtoMessage() {}

func (x *RunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerResponse.ProtoReflect.Descriptor instead.
func (*RunnerResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{6}
}

func (x *RunnerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunnerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RunnerResponse) GetBuildScript() string {
	if x != nil {
		return x.BuildScript
	}
	return ""
}

func (x *RunnerResponse) GetRunScript() string {
	if x != nil {
		return x.RunScript
	}
	return ""
}

func (x *RunnerResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RunnerResponse) GetInitialFiles() []*File {
	if x != nil {
		return x.InitialFiles
	}
	return nil
}

type CreateRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRunnerRequest) Reset() {
	*x = CreateRunnerRequest{}
	mi := &file_config_v1_runners_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunnerRequest) ProtoMessage() {}

func (x *CreateRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunnerRequest.ProtoReflect.Descriptor instead.
func (*CreateRunnerRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRunnerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRunnerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRunnerResponse) Reset() {
	*x = CreateRunnerResponse{}
	mi := &file_config_v1_runners_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunnerResponse) ProtoMessage() {}

func (x *CreateRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunnerResponse.ProtoReflect.Descriptor instead.
func (*CreateRunnerResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRunnerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	BuildScript   *string                `protobuf:"bytes,3,opt,name=build_script,json=buildScript,proto3,oneof" json:"build_script,omitempty"`
	RunScript     *string                `protobuf:"bytes,4,opt,name=run_script,json=runScript,proto3,oneof" json:"run_script,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	InitialFiles  []*File                `protobuf:"bytes,6,rep,name=initial_files,json=initialFiles,proto3" json:"initial_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRunnerRequest) Reset() {
	*x = UpdateRunnerRequest{}
	mi := &file_config_v1_runners_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRunnerRequest) ProtoMessage() {}

func (x *UpdateRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRunnerRequest.ProtoReflect.Descriptor instead.
func (*UpdateRunnerRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRunnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRunnerRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRunnerRequest) GetBuildScript() string {
	if x != nil && x.BuildScript != nil {
		return *x.BuildScript
	}
	return ""
}

func (x *UpdateRunnerRequest) GetRunScript() string {
	if x != nil && x.RunScript != nil {
		return *x.RunScript
	}
	return ""
}

func (x *UpdateRunnerRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateRunnerRequest) GetInitialFiles() []*File {
	if x != nil {
		return x.InitialFiles
	}
	return nil
}

type DeleteRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRunnerRequest) Reset() {
	*x = DeleteRunnerRequest{}
	mi := &file_config_v1_runners_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunnerRequest) ProtoMessage() {}

func (x *DeleteRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunnerRequest.ProtoReflect.Descriptor instead.
func (*DeleteRunnerRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRunnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_config_v1_runners_proto protoreflect.FileDescriptor

const file_config_v1_runners_proto_rawDesc = "" +
	"\n" +
	"\x17config/v1/runners.proto\x12\tconfig.v1\x1a\x1aconfig/v1/pagination.proto\x1a\x14config/v1/file.proto\"\xd4\x01\n" +
	"\x14RunnerPaginationData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fbuild_script\x18\x03 \x01(\tR\vbuildScript\x12\x1d\n" +
	"\n" +
	"run_script\x18\x04 \x01(\tR\trunScript\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x124\n" +
	"\rinitial_files\x18\x06 \x03(\v2\x0f.config.v1.FileR\finitialFiles\"\x84\x01\n" +
	"\x1bGetRunnersPaginationRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.config.v1.PaginationRequestR\n" +
	"pagination\x12'\n" +
	"\x0finclude_scripts\x18\x02 \x01(\bR\x0eincludeScripts\"o\n" +
	"\x1cGetRunnersPaginationResponse\x129\n" +
	"\arunners\x18\x01 \x03(\v2\x1f.config.v1.RunnerPaginationDataR\arunners\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\"\n" +
	"\x10GetRunnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"j\n" +
	"\x14GetAllRunnersRequest\x12)\n" +
	"\x10include_metadata\x18\x01 \x01(\bR\x0fincludeMetadata\x12'\n" +
	"\x0finclude_scripts\x18\x02 \x01(\bR\x0eincludeScripts\"L\n" +
	"\x15GetAllRunnersResponse\x123\n" +
	"\arunners\x18\x01 \x03(\v2\x19.config.v1.RunnerResponseR\arunners\"\xce\x01\n" +
	"\x0eRunnerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fbuild_script\x18\x03 \x01(\tR\vbuildScript\x12\x1d\n" +
	"\n" +
	"run_script\x18\x04 \x01(\tR\trunScript\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x124\n" +
	"\rinitial_files\x18\x06 \x03(\v2\x0f.config.v1.FileR\finitialFiles\"W\n" +
	"\x13CreateRunnerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescriptionJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04\"&\n" +
	"\x14CreateRunnerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa0\x02\n" +
	"\x13UpdateRunnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12&\n" +
	"\fbuild_script\x18\x03 \x01(\tH\x01R\vbuildScript\x88\x01\x01\x12\"\n" +
	"\n" +
	"run_script\x18\x04 \x01(\tH\x02R\trunScript\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01\x124\n" +
	"\rinitial_files\x18\x06 \x03(\v2\x0f.config.v1.FileR\finitialFilesB\a\n" +
	"\x05_nameB\x0f\n" +
	"\r_build_scriptB\r\n" +
	"\v_run_scriptB\x0e\n" +
	"\f_description\"%\n" +
	"\x13DeleteRunnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB\x94\x01\n" +
	"\rcom.config.v1B\fRunnersProtoP\x01Z0github.com/CSKU-Lab/config-server/grpc/config/v1\xa2\x02\x03CXX\xaa\x02\tConfig.V1\xca\x02\tConfig\\V1\xe2\x02\x15Config\\V1\\GPBMetadata\xea\x02\n" +
	"Config::V1b\x06proto3"

var (
	file_config_v1_runners_proto_rawDescOnce sync.Once
	file_config_v1_runners_proto_rawDescData []byte
)

func file_config_v1_runners_proto_rawDescGZIP() []byte {
	file_config_v1_runners_proto_rawDescOnce.Do(func() {
		file_config_v1_runners_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_runners_proto_rawDesc), len(file_config_v1_runners_proto_rawDesc)))
	})
	return file_config_v1_runners_proto_rawDescData
}

var file_config_v1_runners_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_config_v1_runners_proto_goTypes = []any{
	(*RunnerPaginationData)(nil),         // 0: config.v1.RunnerPaginationData
	(*GetRunnersPaginationRequest)(nil),  // 1: config.v1.GetRunnersPaginationRequest
	(*GetRunnersPaginationResponse)(nil), // 2: config.v1.GetRunnersPaginationResponse
	(*GetRunnerRequest)(nil),             // 3: config.v1.GetRunnerRequest
	(*GetAllRunnersRequest)(nil),         // 4: config.v1.GetAllRunnersRequest
	(*GetAllRunnersResponse)(nil),        // 5: config.v1.GetAllRunnersResponse
	(*RunnerResponse)(nil),               // 6: config.v1.RunnerResponse
	(*CreateRunnerRequest)(nil),          // 7: config.v1.CreateRunnerRequest
	(*CreateRunnerResponse)(nil),         // 8: config.v1.CreateRunnerResponse
	(*UpdateRunnerRequest)(nil),          // 9: config.v1.UpdateRunnerRequest
	(*DeleteRunnerRequest)(nil),          // 10: config.v1.DeleteRunnerRequest
	(*File)(nil),                         // 11: config.v1.File
	(*PaginationRequest)(nil),            // 12: config.v1.PaginationRequest
}
var file_config_v1_runners_proto_depIdxs = []int32{
	11, // 0: config.v1.RunnerPaginationData.initial_files:type_name -> config.v1.File
	12, // 1: config.v1.GetRunnersPaginationRequest.pagination:type_name -> config.v1.PaginationRequest
	0,  // 2: config.v1.GetRunnersPaginationResponse.runners:type_name -> config.v1.RunnerPaginationData
	6,  // 3: config.v1.GetAllRunnersResponse.runners:type_name -> config.v1.RunnerResponse
	11, // 4: config.v1.RunnerResponse.initial_files:type_name -> config.v1.File
	11, // 5: config.v1.UpdateRunnerRequest.initial_files:type_name -> config.v1.File
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_config_v1_runners_proto_init() }
func file_config_v1_runners_proto_init() {
	if File_config_v1_runners_proto != nil {
		return
	}
	file_config_v1_pagination_proto_init()
	file_config_v1_file_proto_init()
	file_config_v1_runners_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_runners_proto_rawDesc), len(file_config_v1_runners_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_v1_runners_proto_goTypes,
		DependencyIndexes: file_config_v1_runners_proto_depIdxs,
		MessageInfos:      file_config_v1_runners_proto_msgTypes,
	}.Build()
	File_config_v1_runners_proto = out.File
	file_config_v1_runners_proto_goTypes = nil
	file_config_v1_runners_proto_depIdxs = nil
}
