// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: config/v1/runners.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRunnersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runners       []*Runner              `protobuf:"bytes,1,rep,name=runners,proto3" json:"runners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunnersResponse) Reset() {
	*x = GetRunnersResponse{}
	mi := &file_config_v1_runners_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnersResponse) ProtoMessage() {}

func (x *GetRunnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnersResponse.ProtoReflect.Descriptor instead.
func (*GetRunnersResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{0}
}

func (x *GetRunnersResponse) GetRunners() []*Runner {
	if x != nil {
		return x.Runners
	}
	return nil
}

type GetRunnersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeName   bool                   `protobuf:"varint,1,opt,name=include_name,json=includeName,proto3" json:"include_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunnersRequest) Reset() {
	*x = GetRunnersRequest{}
	mi := &file_config_v1_runners_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunnersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnersRequest) ProtoMessage() {}

func (x *GetRunnersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnersRequest.ProtoReflect.Descriptor instead.
func (*GetRunnersRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{1}
}

func (x *GetRunnersRequest) GetIncludeName() bool {
	if x != nil {
		return x.IncludeName
	}
	return false
}

type GetRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IncludeName   bool                   `protobuf:"varint,2,opt,name=include_name,json=includeName,proto3" json:"include_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunnerRequest) Reset() {
	*x = GetRunnerRequest{}
	mi := &file_config_v1_runners_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnerRequest) ProtoMessage() {}

func (x *GetRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnerRequest.ProtoReflect.Descriptor instead.
func (*GetRunnerRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{2}
}

func (x *GetRunnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRunnerRequest) GetIncludeName() bool {
	if x != nil {
		return x.IncludeName
	}
	return false
}

type Runner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	BuildScript   string                 `protobuf:"bytes,3,opt,name=build_script,json=buildScript,proto3" json:"build_script,omitempty"`
	RunScript     string                 `protobuf:"bytes,4,opt,name=run_script,json=runScript,proto3" json:"run_script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Runner) Reset() {
	*x = Runner{}
	mi := &file_config_v1_runners_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runner) ProtoMessage() {}

func (x *Runner) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runner.ProtoReflect.Descriptor instead.
func (*Runner) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{3}
}

func (x *Runner) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Runner) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Runner) GetBuildScript() string {
	if x != nil {
		return x.BuildScript
	}
	return ""
}

func (x *Runner) GetRunScript() string {
	if x != nil {
		return x.RunScript
	}
	return ""
}

type RunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BuildScript   *string                `protobuf:"bytes,3,opt,name=build_script,json=buildScript,proto3,oneof" json:"build_script,omitempty"`
	RunScript     string                 `protobuf:"bytes,4,opt,name=run_script,json=runScript,proto3" json:"run_script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerResponse) Reset() {
	*x = RunnerResponse{}
	mi := &file_config_v1_runners_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerResponse) ProtoMessage() {}

func (x *RunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerResponse.ProtoReflect.Descriptor instead.
func (*RunnerResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{4}
}

func (x *RunnerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunnerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RunnerResponse) GetBuildScript() string {
	if x != nil && x.BuildScript != nil {
		return *x.BuildScript
	}
	return ""
}

func (x *RunnerResponse) GetRunScript() string {
	if x != nil {
		return x.RunScript
	}
	return ""
}

type AddRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BuildScript   *string                `protobuf:"bytes,2,opt,name=build_script,json=buildScript,proto3,oneof" json:"build_script,omitempty"`
	RunScript     string                 `protobuf:"bytes,3,opt,name=run_script,json=runScript,proto3" json:"run_script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRunnerRequest) Reset() {
	*x = AddRunnerRequest{}
	mi := &file_config_v1_runners_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRunnerRequest) ProtoMessage() {}

func (x *AddRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRunnerRequest.ProtoReflect.Descriptor instead.
func (*AddRunnerRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{5}
}

func (x *AddRunnerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddRunnerRequest) GetBuildScript() string {
	if x != nil && x.BuildScript != nil {
		return *x.BuildScript
	}
	return ""
}

func (x *AddRunnerRequest) GetRunScript() string {
	if x != nil {
		return x.RunScript
	}
	return ""
}

type UpdateRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	BuildScript   *string                `protobuf:"bytes,3,opt,name=build_script,json=buildScript,proto3,oneof" json:"build_script,omitempty"`
	RunScript     *string                `protobuf:"bytes,4,opt,name=run_script,json=runScript,proto3,oneof" json:"run_script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRunnerRequest) Reset() {
	*x = UpdateRunnerRequest{}
	mi := &file_config_v1_runners_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRunnerRequest) ProtoMessage() {}

func (x *UpdateRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRunnerRequest.ProtoReflect.Descriptor instead.
func (*UpdateRunnerRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRunnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRunnerRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRunnerRequest) GetBuildScript() string {
	if x != nil && x.BuildScript != nil {
		return *x.BuildScript
	}
	return ""
}

func (x *UpdateRunnerRequest) GetRunScript() string {
	if x != nil && x.RunScript != nil {
		return *x.RunScript
	}
	return ""
}

type DeleteRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRunnerRequest) Reset() {
	*x = DeleteRunnerRequest{}
	mi := &file_config_v1_runners_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunnerRequest) ProtoMessage() {}

func (x *DeleteRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_runners_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunnerRequest.ProtoReflect.Descriptor instead.
func (*DeleteRunnerRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_runners_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRunnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_config_v1_runners_proto protoreflect.FileDescriptor

const file_config_v1_runners_proto_rawDesc = "" +
	"\n" +
	"\x17config/v1/runners.proto\x12\tconfig.v1\"A\n" +
	"\x12GetRunnersResponse\x12+\n" +
	"\arunners\x18\x01 \x03(\v2\x11.config.v1.RunnerR\arunners\"6\n" +
	"\x11GetRunnersRequest\x12!\n" +
	"\finclude_name\x18\x01 \x01(\bR\vincludeName\"E\n" +
	"\x10GetRunnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\finclude_name\x18\x02 \x01(\bR\vincludeName\"|\n" +
	"\x06Runner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12!\n" +
	"\fbuild_script\x18\x03 \x01(\tR\vbuildScript\x12\x1d\n" +
	"\n" +
	"run_script\x18\x04 \x01(\tR\trunScriptB\a\n" +
	"\x05_name\"\x8c\x01\n" +
	"\x0eRunnerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\fbuild_script\x18\x03 \x01(\tH\x00R\vbuildScript\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"run_script\x18\x04 \x01(\tR\trunScriptB\x0f\n" +
	"\r_build_script\"~\n" +
	"\x10AddRunnerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\fbuild_script\x18\x02 \x01(\tH\x00R\vbuildScript\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"run_script\x18\x03 \x01(\tR\trunScriptB\x0f\n" +
	"\r_build_script\"\xb3\x01\n" +
	"\x13UpdateRunnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12&\n" +
	"\fbuild_script\x18\x03 \x01(\tH\x01R\vbuildScript\x88\x01\x01\x12\"\n" +
	"\n" +
	"run_script\x18\x04 \x01(\tH\x02R\trunScript\x88\x01\x01B\a\n" +
	"\x05_nameB\x0f\n" +
	"\r_build_scriptB\r\n" +
	"\v_run_script\"%\n" +
	"\x13DeleteRunnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB\x94\x01\n" +
	"\rcom.config.v1B\fRunnersProtoP\x01Z0github.com/CSKU-Lab/config-server/grpc/config/v1\xa2\x02\x03CXX\xaa\x02\tConfig.V1\xca\x02\tConfig\\V1\xe2\x02\x15Config\\V1\\GPBMetadata\xea\x02\n" +
	"Config::V1b\x06proto3"

var (
	file_config_v1_runners_proto_rawDescOnce sync.Once
	file_config_v1_runners_proto_rawDescData []byte
)

func file_config_v1_runners_proto_rawDescGZIP() []byte {
	file_config_v1_runners_proto_rawDescOnce.Do(func() {
		file_config_v1_runners_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_runners_proto_rawDesc), len(file_config_v1_runners_proto_rawDesc)))
	})
	return file_config_v1_runners_proto_rawDescData
}

var file_config_v1_runners_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_config_v1_runners_proto_goTypes = []any{
	(*GetRunnersResponse)(nil),  // 0: config.v1.GetRunnersResponse
	(*GetRunnersRequest)(nil),   // 1: config.v1.GetRunnersRequest
	(*GetRunnerRequest)(nil),    // 2: config.v1.GetRunnerRequest
	(*Runner)(nil),              // 3: config.v1.Runner
	(*RunnerResponse)(nil),      // 4: config.v1.RunnerResponse
	(*AddRunnerRequest)(nil),    // 5: config.v1.AddRunnerRequest
	(*UpdateRunnerRequest)(nil), // 6: config.v1.UpdateRunnerRequest
	(*DeleteRunnerRequest)(nil), // 7: config.v1.DeleteRunnerRequest
}
var file_config_v1_runners_proto_depIdxs = []int32{
	3, // 0: config.v1.GetRunnersResponse.runners:type_name -> config.v1.Runner
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_v1_runners_proto_init() }
func file_config_v1_runners_proto_init() {
	if File_config_v1_runners_proto != nil {
		return
	}
	file_config_v1_runners_proto_msgTypes[3].OneofWrappers = []any{}
	file_config_v1_runners_proto_msgTypes[4].OneofWrappers = []any{}
	file_config_v1_runners_proto_msgTypes[5].OneofWrappers = []any{}
	file_config_v1_runners_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_runners_proto_rawDesc), len(file_config_v1_runners_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_v1_runners_proto_goTypes,
		DependencyIndexes: file_config_v1_runners_proto_depIdxs,
		MessageInfos:      file_config_v1_runners_proto_msgTypes,
	}.Build()
	File_config_v1_runners_proto = out.File
	file_config_v1_runners_proto_goTypes = nil
	file_config_v1_runners_proto_depIdxs = nil
}
