// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: config/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_config_v1_service_proto protoreflect.FileDescriptor

const file_config_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x17config/v1/service.proto\x12\tconfig.v1\x1a\x18config/v1/compares.proto\x1a\x17config/v1/runners.proto\x1a\x1bgoogle/protobuf/empty.proto2\xfd\a\n" +
	"\rConfigService\x12Q\n" +
	"\fCreateRunner\x12\x1e.config.v1.CreateRunnerRequest\x1a\x1f.config.v1.CreateRunnerResponse\"\x00\x12i\n" +
	"\x14GetRunnersPagination\x12&.config.v1.GetRunnersPaginationRequest\x1a'.config.v1.GetRunnersPaginationResponse\"\x00\x12E\n" +
	"\tGetRunner\x12\x1b.config.v1.GetRunnerRequest\x1a\x19.config.v1.RunnerResponse\"\x00\x12H\n" +
	"\fUpdateRunner\x12\x1e.config.v1.UpdateRunnerRequest\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\fDeleteRunner\x12\x1e.config.v1.DeleteRunnerRequest\x1a\x16.google.protobuf.Empty\"\x00\x12T\n" +
	"\rGetAllRunners\x12\x1f.config.v1.GetAllRunnersRequest\x1a .config.v1.GetAllRunnersResponse\"\x00\x12T\n" +
	"\rCreateCompare\x12\x1f.config.v1.CreateCompareRequest\x1a .config.v1.CreateCompareResponse\"\x00\x12l\n" +
	"\x15GetComparesPagination\x12'.config.v1.GetComparesPaginationRequest\x1a(.config.v1.GetComparesPaginationResponse\"\x00\x12H\n" +
	"\n" +
	"GetCompare\x12\x1c.config.v1.GetCompareRequest\x1a\x1a.config.v1.CompareResponse\"\x00\x12W\n" +
	"\x0eGetAllCompares\x12 .config.v1.GetAllComparesRequest\x1a!.config.v1.GetAllComparesResponse\"\x00\x12J\n" +
	"\rUpdateCompare\x12\x1f.config.v1.UpdateCompareRequest\x1a\x16.google.protobuf.Empty\"\x00\x12J\n" +
	"\rDeleteCompare\x12\x1f.config.v1.DeleteCompareRequest\x1a\x16.google.protobuf.Empty\"\x00B\x94\x01\n" +
	"\rcom.config.v1B\fServiceProtoP\x01Z0github.com/CSKU-Lab/config-server/grpc/config/v1\xa2\x02\x03CXX\xaa\x02\tConfig.V1\xca\x02\tConfig\\V1\xe2\x02\x15Config\\V1\\GPBMetadata\xea\x02\n" +
	"Config::V1b\x06proto3"

var file_config_v1_service_proto_goTypes = []any{
	(*CreateRunnerRequest)(nil),           // 0: config.v1.CreateRunnerRequest
	(*GetRunnersPaginationRequest)(nil),   // 1: config.v1.GetRunnersPaginationRequest
	(*GetRunnerRequest)(nil),              // 2: config.v1.GetRunnerRequest
	(*UpdateRunnerRequest)(nil),           // 3: config.v1.UpdateRunnerRequest
	(*DeleteRunnerRequest)(nil),           // 4: config.v1.DeleteRunnerRequest
	(*GetAllRunnersRequest)(nil),          // 5: config.v1.GetAllRunnersRequest
	(*CreateCompareRequest)(nil),          // 6: config.v1.CreateCompareRequest
	(*GetComparesPaginationRequest)(nil),  // 7: config.v1.GetComparesPaginationRequest
	(*GetCompareRequest)(nil),             // 8: config.v1.GetCompareRequest
	(*GetAllComparesRequest)(nil),         // 9: config.v1.GetAllComparesRequest
	(*UpdateCompareRequest)(nil),          // 10: config.v1.UpdateCompareRequest
	(*DeleteCompareRequest)(nil),          // 11: config.v1.DeleteCompareRequest
	(*CreateRunnerResponse)(nil),          // 12: config.v1.CreateRunnerResponse
	(*GetRunnersPaginationResponse)(nil),  // 13: config.v1.GetRunnersPaginationResponse
	(*RunnerResponse)(nil),                // 14: config.v1.RunnerResponse
	(*emptypb.Empty)(nil),                 // 15: google.protobuf.Empty
	(*GetAllRunnersResponse)(nil),         // 16: config.v1.GetAllRunnersResponse
	(*CreateCompareResponse)(nil),         // 17: config.v1.CreateCompareResponse
	(*GetComparesPaginationResponse)(nil), // 18: config.v1.GetComparesPaginationResponse
	(*CompareResponse)(nil),               // 19: config.v1.CompareResponse
	(*GetAllComparesResponse)(nil),        // 20: config.v1.GetAllComparesResponse
}
var file_config_v1_service_proto_depIdxs = []int32{
	0,  // 0: config.v1.ConfigService.CreateRunner:input_type -> config.v1.CreateRunnerRequest
	1,  // 1: config.v1.ConfigService.GetRunnersPagination:input_type -> config.v1.GetRunnersPaginationRequest
	2,  // 2: config.v1.ConfigService.GetRunner:input_type -> config.v1.GetRunnerRequest
	3,  // 3: config.v1.ConfigService.UpdateRunner:input_type -> config.v1.UpdateRunnerRequest
	4,  // 4: config.v1.ConfigService.DeleteRunner:input_type -> config.v1.DeleteRunnerRequest
	5,  // 5: config.v1.ConfigService.GetAllRunners:input_type -> config.v1.GetAllRunnersRequest
	6,  // 6: config.v1.ConfigService.CreateCompare:input_type -> config.v1.CreateCompareRequest
	7,  // 7: config.v1.ConfigService.GetComparesPagination:input_type -> config.v1.GetComparesPaginationRequest
	8,  // 8: config.v1.ConfigService.GetCompare:input_type -> config.v1.GetCompareRequest
	9,  // 9: config.v1.ConfigService.GetAllCompares:input_type -> config.v1.GetAllComparesRequest
	10, // 10: config.v1.ConfigService.UpdateCompare:input_type -> config.v1.UpdateCompareRequest
	11, // 11: config.v1.ConfigService.DeleteCompare:input_type -> config.v1.DeleteCompareRequest
	12, // 12: config.v1.ConfigService.CreateRunner:output_type -> config.v1.CreateRunnerResponse
	13, // 13: config.v1.ConfigService.GetRunnersPagination:output_type -> config.v1.GetRunnersPaginationResponse
	14, // 14: config.v1.ConfigService.GetRunner:output_type -> config.v1.RunnerResponse
	15, // 15: config.v1.ConfigService.UpdateRunner:output_type -> google.protobuf.Empty
	15, // 16: config.v1.ConfigService.DeleteRunner:output_type -> google.protobuf.Empty
	16, // 17: config.v1.ConfigService.GetAllRunners:output_type -> config.v1.GetAllRunnersResponse
	17, // 18: config.v1.ConfigService.CreateCompare:output_type -> config.v1.CreateCompareResponse
	18, // 19: config.v1.ConfigService.GetComparesPagination:output_type -> config.v1.GetComparesPaginationResponse
	19, // 20: config.v1.ConfigService.GetCompare:output_type -> config.v1.CompareResponse
	20, // 21: config.v1.ConfigService.GetAllCompares:output_type -> config.v1.GetAllComparesResponse
	15, // 22: config.v1.ConfigService.UpdateCompare:output_type -> google.protobuf.Empty
	15, // 23: config.v1.ConfigService.DeleteCompare:output_type -> google.protobuf.Empty
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_config_v1_service_proto_init() }
func file_config_v1_service_proto_init() {
	if File_config_v1_service_proto != nil {
		return
	}
	file_config_v1_compares_proto_init()
	file_config_v1_runners_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_service_proto_rawDesc), len(file_config_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_v1_service_proto_goTypes,
		DependencyIndexes: file_config_v1_service_proto_depIdxs,
	}.Build()
	File_config_v1_service_proto = out.File
	file_config_v1_service_proto_goTypes = nil
	file_config_v1_service_proto_depIdxs = nil
}
